# -*- coding: utf-8 -*-
"""
Extract all EI triplets for each SMILES from the API result JSON.

Input supports:
1) Output file generated by run_ei_ms_api.py, where each record contains "model_output".
2) Direct model-output JSON, where each record itself contains "triples".

Output format:
[
  {
    "id": 1,
    "name": "Methane",
    "smiles": "C",
    "formula": "CH4",
    "mw": "16",
    "triplets": [
      ["smiles_fragment: C", "Molecular ion", "CH4+ (m/z 16)"],
      ["smiles_fragment: C", "Dehydrogenation / Sequential dehydrogenation", "CH3+ (m/z 15)"]
    ]
  }
]

Usage:
python extract_ei_triplets.py \
  --input_file ./outputs/acyclic_alkane_ei_results.json \
  --output_file ./outputs/acyclic_alkane_triplets_only.json

Optional:
--keep_mz          Keep source m/z for each triplet.
--include_invalid  Also keep invalid m/z entries.
"""

import argparse
import json
import os
from typing import Any, Dict, List, Optional


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input_file",
        type=str,
        required=True,
        help="Input JSON file generated by the API calling script.",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        required=True,
        help="Output JSON file containing only molecule info and merged triplets.",
    )
    parser.add_argument(
        "--keep_mz",
        action="store_true",
        help="If set, each output triplet will be stored with its source m/z.",
    )
    parser.add_argument(
        "--include_invalid",
        action="store_true",
        help="If set, invalid or empty triplet entries will also be kept.",
    )
    return parser.parse_args()


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(obj: Any, path: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def safe_int(x: Any) -> int:
    try:
        return int(x)
    except Exception:
        return -1


def get_model_output(record: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compatible with:
    1) Wrapper result from run_ei_ms_api.py: record["model_output"]
    2) Direct model JSON output: record itself
    """
    model_output = record.get("model_output")
    if isinstance(model_output, dict):
        return model_output
    return record


def get_basic_info(record: Dict[str, Any], model_output: Dict[str, Any]) -> Dict[str, Any]:
    """
    Prefer outer wrapper fields. If missing, fall back to model_output.
    """
    return {
        "id": record.get("id", model_output.get("id", None)),
        "name": record.get("name", model_output.get("name", "")),
        "smiles": record.get("smiles", model_output.get("smiles", model_output.get("source_smiles", ""))),
        "formula": record.get("formula", model_output.get("formula", "")),
        "mw": record.get("mw", model_output.get("mw", "")),
    }


def normalize_triplet(t: Any) -> Optional[List[str]]:
    """
    Keep only legal triplet:
    ["precursor", "mechanism", "product_ion"]
    """
    if isinstance(t, list) and len(t) == 3:
        return [str(t[0]), str(t[1]), str(t[2])]
    return None


def extract_triplets_from_one_record(
    record: Dict[str, Any],
    keep_mz: bool = False,
    include_invalid: bool = False,
) -> Dict[str, Any]:
    model_output = get_model_output(record)
    output_item = get_basic_info(record, model_output)

    triples_dict = model_output.get("triples", {})
    merged_triplets: List[Any] = []

    if not isinstance(triples_dict, dict):
        output_item["triplets"] = []
        output_item["extract_warning"] = "model_output.triples is missing or not a dict"
        return output_item

    # Sort m/z from high to low for easier global inspection
    sorted_mz_items = sorted(
        triples_dict.items(),
        key=lambda kv: safe_int(kv[0]),
        reverse=True,
    )

    for mz, mz_item in sorted_mz_items:
        if not isinstance(mz_item, dict):
            continue

        status = mz_item.get("triplet_status", None)
        triplet_list = mz_item.get("triplet", [])

        # Default: skip invalid or empty triplet entries
        if status == "invalid" or not triplet_list:
            if include_invalid:
                invalid_item = {
                    "mz": str(mz),
                    "triplet_status": status,
                    "invalid_reason": mz_item.get("invalid_reason", None),
                    "triplet": [],
                }
                merged_triplets.append(invalid_item if keep_mz else [])
            continue

        # triplet_list should be:
        # [
        #   ["precursor", "mechanism", "product_ion"],
        #   ["precursor", "mechanism", "product_ion"]
        # ]
        for t in triplet_list:
            normalized = normalize_triplet(t)
            if normalized is None:
                continue

            if keep_mz:
                merged_triplets.append({
                    "mz": str(mz),
                    "triplet": normalized,
                })
            else:
                merged_triplets.append(normalized)

    output_item["triplets"] = merged_triplets
    return output_item


def main() -> None:
    args = parse_args()

    data = load_json(args.input_file)

    # Also support a single-object JSON input
    if isinstance(data, dict):
        data = [data]

    if not isinstance(data, list):
        raise ValueError("Input JSON must be a list or a single dict.")

    outputs = []

    for i, record in enumerate(data, start=1):
        if not isinstance(record, dict):
            continue

        item = extract_triplets_from_one_record(
            record=record,
            keep_mz=args.keep_mz,
            include_invalid=args.include_invalid,
        )
        outputs.append(item)

        print(
            f"[{i}/{len(data)}] "
            f"id={item.get('id')} "
            f"name={item.get('name')} "
            f"triplets={len(item.get('triplets', []))}"
        )

    save_json(outputs, args.output_file)

    print("=" * 80)
    print(f"Saved {len(outputs)} records to: {args.output_file}")


if __name__ == "__main__":
    main()

"""
python extract_smile_triplts.py --input_file ./alkene_outputs/openai_gpt41_test_results.json --output_file ./alkene_outputs/openai_gpt41_test_results_extract_1.json
"""

