# -*- coding: utf-8 -*-
"""
python run_openai_aromatic_hydrocarbon_judge.py --input_file ./aromatic_hydrocarbon_outputs/openai_gpt41_test_results_extract.json --output_file ./aromatic_hydrocarbon_outputs/openai_gpt41_test_results_judge_all.json --corrected_output_file ./aromatic_hydrocarbon_outputs/openai_gpt41_test_results_judge_extract.json --api_key xx --model gpt-4.1 --temperature 0.0 --id_min 1 --id_max 1957 --sleep 1
"""

import argparse
import copy
import json
import os
import re
import time
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

from openai import OpenAI


# ============================================================
# 1. System prompt: no-delete EI-MS triplet Judge
# ============================================================

SYSTEM_PROMPT = r"""
You are a professional review-style Judge for EI-MS fragmentation triplets.

Your responsibility is to verify whether an existing triplet is chemically reasonable
and, when it is not reasonable, revise it into a chemically reasonable triplet that
still produces the same target product ion.

You are not a free generator.

You are not required to find the uniquely correct mechanism.

Your task is:

* accept chemically reasonable triplets;
* revise clearly incorrect, unreasonable, or EI-inconsistent triplets;
* always preserve the target product ion unless the product ion formula/m/z itself is inconsistent.

────────────────────────
No-delete principle
────────────────────────

The verdict "delete" is forbidden.

You must output only:

"accept" or "revise"

If the original triplet is chemically unreasonable, do not delete it. Instead, revise
the precursor and/or mechanism so that the same target product ion is generated by
a chemically reasonable pathway.

If the original precursor_mz is wrong, replace it with:
1. a valid previous verified same-carbon higher-hydrogen precursor_mz, or
2. a valid structure-driven smiles_fragment from the molecule.

If the original mechanism is wrong, replace it with the chemically reasonable mechanism.

Never output:
"verdict": "delete"

Never output:
"verdict": "revise",
"corrected_triplet": []

────────────────────────
Mandatory arithmetic gate
────────────────────────

Before chemical reasoning, check arithmetic consistency.

1. "Isotopic peak" is valid only when:
   product_mz > precursor_mz
   and product_mz - precursor_mz = 1 or 2.

   If product_mz < precursor_mz, revise the mechanism.
   Never accept an M−1 or M−2 ion as an isotopic peak.

2. "Dehydrogenation / Sequential dehydrogenation" is valid only when:
   - carbon number is conserved;
   - the precursor ion is explicitly supported;
   - the weak-peak-to-strong-peak rule is not violated.

3. "Neutral loss" is valid only when:
   precursor_mz > product_mz.

If a triplet fails this arithmetic gate, it must be revised regardless of other
chemical plausibility.

────────────────────────
Mechanism enumeration enforcement
────────────────────────

The mechanism field corrected_triplet[1] must be exactly one of the 13 allowed mechanisms:

Molecular ion
Isotopic peak
Alpha-cleavage
Sigma-bond cleavage
Benzylic cleavage
Allylic cleavage
McLafferty rearrangement
Neutral loss
Retro-Diels–Alder fragmentation
Hydrogen transfer
Radical-ion rearrangement
Dehydrogenation / Sequential dehydrogenation
Ring cleavage / Ring rearrangement

Do not append any modifier to the mechanism field.

Forbidden examples:
"Neutral loss (C2H4)"
"Neutral loss (C3H7)"
"Neutral loss (unsupported 32 Da)"
"Protonation"
"Hydride addition"

If the neutral fragment or extra explanation is useful, put it in the reason field only, not in corrected_triplet[1].

────────────────────────
Corrected triplet precursor format enforcement
────────────────────────

The precursor field corrected_triplet[0] must always begin with exactly one of:

"precursor_mz: "
"smiles_fragment: "

Direct ion descriptions are forbidden in corrected_triplet[0].

Forbidden examples:
"C20H20+ (m/z 260)"
"C16H10+ (m/z 202)"
"Molecular ion"

Correct examples:
"precursor_mz: 260"
"smiles_fragment: c1ccc2c(c1)"

────────────────────────
Core principle
────────────────────────

EI fragmentation often admits multiple chemically reasonable pathways.

Therefore:

Accept any chemically reasonable explanation.

Revise only chemically unreasonable explanations.

If the original triplet is chemically reasonable, accept it even if another explanation
is more common, more canonical, or more preferred.

Do not modify a reasonable triplet merely for stylistic consistency.

A more preferred explanation is not sufficient reason for revision.

Revise only when the original precursor, product ion, or mechanism is chemically
invalid or clearly unreasonable.

────────────────────────
Revision priority
────────────────────────

The Judge must work according to the following priority order:

1. Whether the product ion formula and m/z are internally consistent.

2. Whether the precursor can support the product ion.

3. Whether the mechanism is clearly wrong.

4. Whether a better explanation exists.

Revision is allowed only when one of the first three items has a problem.

Do not revise a reasonable triplet merely because a better explanation exists.

────────────────────────
Key inspection items
────────────────────────

Check:

1. Whether the formula matches the m/z.

2. Whether the product ion carbon number is compatible with the molecule.

3. Whether the precursor can support the product ion.

4. Whether the mechanism conflicts with the structure.

5. Whether the weak-peak-to-strong-peak rule is violated if spectrum evidence is available.

────────────────────────
Same-carbon dehydrogenation gate
────────────────────────

For aromatic and PAH triplet judging, do not prefer dehydrogenation merely because a same-carbon higher-hydrogen ion exists.

"Dehydrogenation / Sequential dehydrogenation" is allowed only when all conditions are satisfied:
1. precursor_mz is explicitly present and supported;
2. precursor and product have the same carbon number;
3. precursor has a higher hydrogen count;
4. precursor intensity is not weaker than product intensity;
5. no chemically reasonable structure-driven aromatic explanation already exists.

If any condition fails, do not revise the triplet to dehydrogenation.


────────────────────────
Wrong precursor replacement rule
────────────────────────

If the original precursor_mz is chemically unsuitable but the product ion is chemically reasonable, revise the precursor with minimal change.

Do not automatically change the mechanism to "Dehydrogenation / Sequential dehydrogenation".

If a valid structure_fragment_candidates_for_product exists and the current or corrected mechanism is chemically reasonable, prefer:
["smiles_fragment: <fragment>", "<chemically reasonable aromatic mechanism>", "<same product ion>"]

For aromatic terminal ions such as C6H5+ (77), C5H5+ (65), C4H3+ (51), and C3H3+ (39), prefer structure-driven aromatic explanations over automatic ion-evolution explanations.


────────────────────────
Heteroatom-containing compound rules
────────────────────────

Only when fragmentation occurs adjacent to a heteroatom is the following mechanism allowed:

"Alpha-cleavage"

For losses such as:

CO
H2O
NH3
H2S
SO2

use:

"Neutral loss"

For pure hydrocarbon molecules, do not use "Neutral loss" for single-H loss that
forms hydrocarbon cations such as CH3+, C2H5+, or C3H7+.

For hydrocarbon alkyl-cation formation, prefer:

"Sigma-bond cleavage"

Reserve "Neutral loss" mainly for stable neutral losses such as CO, H2O, NH3,
H2S, SO2, or clearly defined neutral molecular eliminations.

────────────────────────
Aromatic and PAH revision rule
────────────────────────

Applicable objects:
- aromatic hydrocarbons
- alkyl-substituted aromatics
- fused-ring aromatics
- PAHs

1. Molecular ion:
For aromatic and PAH compounds, strong molecular ions are common.
If the original triplet correctly assigns the molecular ion, accept it.

2. Isotopic peak:
Accept "Isotopic peak" only when product_mz = precursor_mz + 1 or +2.
Never accept M−1 or M−2 as an isotopic peak.

3. Alkyl-substituted aromatics:
For alkylbenzenes, C7H7+ (m/z 91) is commonly explained by "Benzylic cleavage"
when the structure contains a benzylic side chain.
Tropylium/benzyl stabilization may be mentioned in the reason, but must not be used as a mechanism label.

4. Aromatic homologous ions:
Do not force 77/91/105/119 or 128/142/156 into serial precursor-product chains merely because they differ by 14 Da.
They may be parallel aromatic terminal ions.

5. m/z 78 and 77:
C6H6+ (m/z 78) retains an intact benzene ring; do not revise it to "Ring cleavage / Ring rearrangement" merely because it is aromatic.
C6H5+ (m/z 77) retains a phenyl ring; do not automatically revise it to 78→77 dehydrogenation unless the precursor is explicitly present, stronger than the product, and the weak-to-strong rule is satisfied.

For alkylbenzenes, C6H5+ (m/z 77) may be accepted as a weak aromatic-ring-retained terminal ion. If a valid C6 aromatic fragment is available, a structure-driven explanation is acceptable; do not force a serial precursor-product path.

6. Ring cleavage / Ring rearrangement:
Use "Ring cleavage / Ring rearrangement" mainly when the aromatic ring system is broken, contracted, rearranged, or converted to smaller aromatic ions such as C5H5+ (m/z 65), C4H3+ (m/z 51), or C3H3+ (m/z 39).

7. Neutral loss:

Use "Neutral loss" only when all of the following are true:

- precursor_mz > product_mz;
- the mass difference corresponds to a chemically meaningful neutral fragment;
- the neutral fragment is structurally plausible for the molecule;
- the precursor is explicitly represented as "precursor_mz: <int>" or a local smiles_fragment that clearly identifies the neutral-loss site.

For fused-ring aromatics and PAHs:

Do not accept or revise to "Neutral loss" merely because the mass difference can be written as a hydrocarbon formula.

If the product ion is a smaller fused-ring aromatic ion, highly unsaturated PAH-like ion, or ring-contracted aromatic ion, and no clear neutral-loss site is identifiable, prefer:

"Ring cleavage / Ring rearrangement"

Common acceptable neutral losses include, when structurally supported:

- CH3· from an alkyl substituent
- C2H2 from aromatic/alkynyl systems
- C2H4 or C3H6 from partially saturated rings or side chains
- H2 from dehydrogenation/aromatization-related processes

Do not append the neutral fragment to corrected_triplet[1].
The mechanism field must remain exactly:

"Neutral loss"

Any neutral-fragment explanation should appear only in the reason field.

8. Accept-over-revise:
If the original aromatic triplet is chemically reasonable, accept it.
Do not revise merely because another aromatic pathway is more common.

────────────────────────
Context usage rule
────────────────────────

The user input may contain:

1. all_original_triplets_for_this_molecule:
   All triplets originally generated for the same molecule. Use this only as contextual evidence.

2. previous_verified_corrected_triplets_for_this_molecule:
   Triplets from the same molecule that have already been judged earlier in the current run
   and have passed code-side chemical consistency checks.

3. same_carbon_higher_h_precursor_candidates:
   Previous verified ions that have the same carbon number as the current product ion
   and a higher hydrogen count.

4. structure_fragment_candidates_for_product:
   Verifiable SMILES substrings from the current molecule whose carbon count matches
   the current product ion.

5. previous_reliable_precursor_triplets_for_this_molecule:
   A stricter subset of previous corrected triplets that may be used as strong
   precursor_mz evidence in later ion-evolution decisions.

6. original_precursor_status:
   Whether the original precursor_mz is already supported as a same-carbon
   higher-hydrogen precursor for the current product ion.

When judging the current triplet:
- You may use previous_verified_corrected_triplets_for_this_molecule as reference evidence.
- Prefer previous_reliable_precursor_triplets_for_this_molecule for selecting precursor_mz candidates.
- If original_precursor_status.is_supported=true and the mechanism is
  "Dehydrogenation / Sequential dehydrogenation", accept the original precursor.
  Do not revise it merely because another higher-hydrogen precursor exists.
- Previous verified corrected triplets are reference evidence, not unquestionable ground truth.
- Before using a previous triplet as a precursor, verify:
  1. its product ion m/z matches the current precursor_mz;
  2. its product ion formula has a compatible carbon number;
  3. the mechanism from that precursor to the current product is chemically valid.
- Do not assume any future triplet has already been corrected.
- Do not use previous corrected triplets to justify carbon-number-changing dehydrogenation.
- Do not modify a chemically reasonable triplet merely because previous corrected triplets provide another possible explanation.

────────────────────────
Output format
────────────────────────

You must output strict JSON only, with no extra explanatory text.

The output JSON must follow exactly this structure:

{
  "id": ...,
  "name": "...",
  "smiles": "...",
  "formula": "...",
  "mw": "...",
  "original_triplet": [...],
  "verdict": "accept | revise",
  "reason": "...",
  "corrected_triplet": [...],
  "overall_quality": "...",
  "major_errors": [...],
  "recommended_strategy": "..."
}

Rules:
- verdict must be only "accept" or "revise".
- If verdict="accept", corrected_triplet must be identical to original_triplet.
- If verdict="revise", corrected_triplet must contain the minimally revised valid triplet.
- corrected_triplet must always be a non-empty 3-element list.
- corrected_triplet must preserve the same product ion as original_triplet unless the product ion formula/m/z itself is internally inconsistent.
- major_errors must be an array. If there is no major error, use [].
- Do not output markdown.
- Do not output comments outside JSON.

Forbidden:
- Never output verdict="delete".
- Never output corrected_triplet=[].
"""


# ============================================================
# 2. Argument parser
# ============================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()

    parser.add_argument("--input_file", type=str, required=True,
                        help="Input JSON file containing extracted triplets for each molecule.")
    parser.add_argument("--output_file", type=str, required=True,
                        help="Full output JSON file containing judge results for every triplet.")
    parser.add_argument("--corrected_output_file", type=str, required=True,
                        help="Output JSON file grouped by id, containing final corrected_triplet lists.")

    parser.add_argument("--api_key", type=str, default=None,
                        help="API key. If not provided, OPENAI_API_KEY will be used.")
    parser.add_argument("--base_url", type=str, default=None,
                        help="Kept only for backward compatibility. Official OpenAI API does not use base_url.")
    parser.add_argument("--model", type=str, default="gpt-4.1", help="Model name.")
    parser.add_argument("--temperature", type=float, default=0.0,
                        help="Recommended to use 0.0 for deterministic judging.")

    parser.add_argument("--start", type=int, default=0, help="Start molecule index after id filtering.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Only process N molecules after start and id filtering.")
    parser.add_argument("--id_min", type=int, default=None,
                        help="Only process molecules with id >= id_min.")
    parser.add_argument("--id_max", type=int, default=None,
                        help="Only process molecules with id <= id_max.")

    parser.add_argument("--sleep", type=float, default=0.0,
                        help="Sleep seconds between triplet-level requests.")
    parser.add_argument("--save_every", type=int, default=1,
                        help="Save intermediate results every N judged triplets.")
    parser.add_argument("--use_json_mode", action="store_true",
                        help="Use response_format={'type':'json_object'} if the API provider supports it.")
    parser.add_argument("--skip_existing", action="store_true",
                        help="If output_file exists, skip triplets already judged by id and triplet_index.")
    parser.add_argument("--keep_failed_original", action="store_true",
                        help="If API fails, keep a deterministic no-delete fallback based on the original triplet.")
    parser.add_argument("--include_unsafe_in_corrected", action="store_true",
                        help="If set, final corrected_output_file will include final corrected triplets even when context_safe=false.")
    parser.add_argument("--semantic_retry", type=int, default=2,
                        help="Number of semantic retries when the model outputs delete/invalid corrected_triplet.")

    return parser.parse_args()


# ============================================================
# 3. Formula / ion / SMILES utilities
# ============================================================

ION_RE = re.compile(
    r"(?P<formula>[A-Z][A-Za-z0-9?]*(?:\+|＋)?(?:[•·])?)\s*"
    r"(?P<isotope_annotation>\[\s*M\s*[+-]\s*\d+\s*\])?\s*"
    r"\(m/z\s*(?P<mz>\d+)\)",
    flags=re.IGNORECASE,
)
FORMULA_RE = re.compile(r"([A-Z][a-z]?)(\d*)")


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(obj: Any, path: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def normalize_triplet(triplet: Any) -> Optional[List[str]]:
    if isinstance(triplet, list) and len(triplet) == 3:
        return [str(triplet[0]), str(triplet[1]), str(triplet[2])]
    return None


def parse_formula_counts(formula: str) -> Dict[str, int]:
    if not isinstance(formula, str):
        return {}

    formula = (
        formula.replace("+", "")
        .replace("＋", "")
        .replace("•", "")
        .replace("·", "")
        .replace("?", "")
    )

    counts: Dict[str, int] = defaultdict(int)
    for element, num in FORMULA_RE.findall(formula):
        counts[element] += int(num) if num else 1

    return dict(counts)


def nominal_mass(counts: Dict[str, int]) -> int:
    mass_table = {
        "H": 1,
        "C": 12,
        "N": 14,
        "O": 16,
        "F": 19,
        "P": 31,
        "S": 32,
        "Cl": 35,
        "Br": 79,
        "I": 127,
    }
    return sum(mass_table.get(element, 0) * n for element, n in counts.items())


def parse_isotope_annotation_offset(annotation: str) -> int:
    """
    Parse isotope annotations placed between the formula and m/z, for example:
    C20H20+ [M+1] (m/z 261).

    Only the extraction/validation support is added here; the original product_ion
    string is not rewritten, so output formatting remains unchanged.
    """
    if not isinstance(annotation, str) or not annotation.strip():
        return 0

    m = re.search(r"M\s*([+-])\s*(\d+)", annotation, flags=re.IGNORECASE)
    if not m:
        return 0

    sign = 1 if m.group(1) == "+" else -1
    return sign * int(m.group(2))


def parse_ion(product_ion: str) -> Optional[Dict[str, Any]]:
    if not isinstance(product_ion, str):
        return None

    m = ION_RE.search(product_ion)
    if not m:
        return None

    formula = m.group("formula")
    isotope_annotation = m.group("isotope_annotation") or ""
    isotope_offset = parse_isotope_annotation_offset(isotope_annotation)
    mz = int(m.group("mz"))
    counts = parse_formula_counts(formula)

    base_nominal_mass = nominal_mass(counts)

    return {
        "formula": formula,
        "mz": mz,
        "counts": counts,
        "carbon": counts.get("C", 0),
        "hydrogen": counts.get("H", 0),
        "nominal_mass": base_nominal_mass,
        "isotope_annotation": isotope_annotation,
        "isotope_offset": isotope_offset,
        "expected_mz": base_nominal_mass + isotope_offset,
        "has_unknown": "?" in formula,
    }


def parse_precursor_mz(precursor: str) -> Optional[int]:
    if not isinstance(precursor, str):
        return None
    m = re.match(r"precursor_mz:\s*(\d+)", precursor.strip())
    return int(m.group(1)) if m else None


def count_c_in_smiles(smiles_fragment: str) -> int:
    if not isinstance(smiles_fragment, str):
        return 0
    # Count both aliphatic carbon "C" and aromatic carbon "c" in SMILES.
    # Keep the original chloride guard so "Cl" is not counted as carbon.
    return len(re.findall(r"C(?!l)|c", smiles_fragment))


def is_balanced_fragment(fragment: str) -> bool:
    balance = 0
    for ch in fragment:
        if ch == "(":
            balance += 1
        elif ch == ")":
            balance -= 1
            if balance < 0:
                return False
    return balance == 0


def parse_smiles_fragment_precursor(precursor: str) -> Tuple[Optional[str], List[str]]:
    if not isinstance(precursor, str) or not precursor.startswith("smiles_fragment:"):
        return None, []

    body = precursor.replace("smiles_fragment:", "", 1).strip()
    parts = body.split("|")
    best = parts[0].strip() if parts else None

    alternatives: List[str] = []
    if len(parts) > 1:
        m = re.search(r"alternatives:\s*\[(.*?)\]", parts[1])
        if m:
            alternatives = [
                x.strip().strip("'\"")
                for x in m.group(1).split(",")
                if x.strip()
            ]

    return best or None, alternatives


def format_smiles_fragment_candidate(candidates: List[str]) -> str:
    unique = list(dict.fromkeys([c for c in candidates if c]))
    if not unique:
        return "smiles_fragment: C"

    best = unique[0]
    alts = unique[1:4]
    if alts:
        return f"smiles_fragment: {best} | alternatives: [{', '.join(alts)}]"
    return f"smiles_fragment: {best}"


def enumerate_smiles_fragment_candidates(smiles: str, target_c: int, max_candidates: int = 8) -> List[str]:
    if not isinstance(smiles, str) or target_c <= 0:
        return []

    candidates: List[str] = []

    # Common exact linear fragment.
    linear = "C" * target_c
    if linear in smiles:
        candidates.append(linear)

    # Enumerate balanced substrings with exactly target_c carbon atoms.
    n = len(smiles)
    for i in range(n):
        for j in range(i + 1, n + 1):
            sub = smiles[i:j]
            if "C" not in sub:
                continue
            if count_c_in_smiles(sub) != target_c:
                continue
            if not sub.startswith("C"):
                continue
            if not (sub.endswith("C") or sub.endswith(")")):
                continue
            if not is_balanced_fragment(sub):
                continue
            if sub in smiles:
                candidates.append(sub)

    # Prefer branch-aware fragments when the source is branched, otherwise shorter exact fragments.
    def sort_key(x: str) -> Tuple[int, int, str]:
        has_branch = 1 if "(" in x or ")" in x else 0
        # branch first; then shorter; then lexical
        return (-has_branch, len(x), x)

    candidates = sorted(list(dict.fromkeys(candidates)), key=sort_key)
    return candidates[:max_candidates]


def get_structure_fragment_candidates(smiles: str, product_ion: str) -> List[str]:
    ion = parse_ion(product_ion)
    if ion is None:
        return []

    return enumerate_smiles_fragment_candidates(smiles, ion["carbon"])


def find_previous_ions_by_mz(previous_verified_triplets: List[List[str]], mz: int) -> List[Dict[str, Any]]:
    matched = []
    for triplet in previous_verified_triplets:
        if not isinstance(triplet, list) or len(triplet) != 3:
            continue
        ion = parse_ion(triplet[2])
        if ion is not None and ion["mz"] == mz:
            matched.append(ion)
    return matched


def get_same_carbon_higher_h_precursor_candidates(
    previous_verified_triplets: List[List[str]],
    product_ion: str,
) -> List[Dict[str, Any]]:
    product = parse_ion(product_ion)
    if product is None:
        return []

    candidates = []
    for triplet in previous_verified_triplets:
        ion = parse_ion(triplet[2]) if isinstance(triplet, list) and len(triplet) == 3 else None
        if ion is None:
            continue
        if ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]:
            candidates.append({
                "precursor_mz": ion["mz"],
                "precursor_ion": triplet[2],
                "source_triplet": triplet,
                "carbon": ion["carbon"],
                "hydrogen": ion["hydrogen"],
            })

    # Prefer nearest higher mass / hydrogen, but any same-carbon higher-H is acceptable.
    candidates.sort(key=lambda x: (x["precursor_mz"]))
    return candidates


def is_alkyl_like_ion(ion: Dict[str, Any]) -> bool:
    c = ion.get("carbon", 0)
    h = ion.get("hydrogen", 0)
    return c > 0 and h >= 2 * c + 1


def is_unsaturated_hydrocarbon_ion(ion: Dict[str, Any]) -> bool:
    c = ion.get("carbon", 0)
    h = ion.get("hydrogen", 0)
    return c > 0 and h < 2 * c + 1


def is_highly_unsaturated_hydrocarbon_ion(ion: Dict[str, Any]) -> bool:
    """
    Target ions such as C2H3+, C3H5+, C3H3+, C4H7+, C5H9+.
    These should generally not be explained by plain Sigma-bond cleavage when
    a dehydrogenation-style explanation is available.

    We intentionally use H <= 2C - 1 rather than H < 2C + 1 so that even-electron
    ions such as C4H8+ are not automatically rewritten away from Sigma-bond cleavage.
    """
    c = ion.get("carbon", 0)
    h = ion.get("hydrogen", 0)
    return c > 0 and h <= 2 * c - 1


def should_avoid_sigma_for_unsaturated_product(mechanism: str, product_ion: str) -> bool:
    if mechanism != "Sigma-bond cleavage":
        return False
    product = parse_ion(product_ion)
    if product is None:
        return False
    return is_highly_unsaturated_hydrocarbon_ion(product)


def choose_dehydrogenation_precursor(
    original_precursor: str,
    previous_verified_triplets: List[List[str]],
    product_ion: str,
) -> Optional[int]:
    """
    Choose a precursor_mz for same-carbon dehydrogenation.

    Priority:
    1. Keep the original precursor_mz if it is already supported by previous verified
       triplets and has the same carbon number with a higher hydrogen count.
    2. Otherwise choose the nearest same-carbon higher-H precursor, rather than
       blindly choosing the highest-H precursor. This avoids over-revising valid
       stepwise dehydrogenation paths.
    """
    product = parse_ion(product_ion)
    if product is None:
        return None

    original_mz = parse_precursor_mz(original_precursor)
    if original_mz is not None:
        previous_ions = find_previous_ions_by_mz(previous_verified_triplets, original_mz)
        for ion in previous_ions:
            if ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]:
                return original_mz

    candidates = get_same_carbon_higher_h_precursor_candidates(
        previous_verified_triplets,
        product_ion,
    )
    if not candidates:
        return None

    # Choose the closest higher-H precursor first; tie-break by smaller m/z.
    candidates.sort(key=lambda x: (x["hydrogen"] - product["hydrogen"], x["precursor_mz"]))
    return candidates[0]["precursor_mz"]


def is_reliable_for_precursor_context(triplet: List[str]) -> bool:
    """
    Decide whether a corrected triplet is strong enough to be reused as
    precursor_mz evidence in later ion-evolution decisions.

    This is intentionally stricter than context_safe:
    - Molecular ion can seed later context.
    - Sigma-bond cleavage with a structure-driven precursor can seed alkyl ions.
    - Dehydrogenation with precursor_mz can seed later dehydrogenation steps.
    - Dehydrogenation with only a smiles_fragment is kept in final output, but is
      not treated as strong precursor_mz evidence by default.
    """
    if not isinstance(triplet, list) or len(triplet) != 3:
        return False

    precursor, mechanism, product_ion = triplet

    if mechanism == "Molecular ion":
        return True

    if mechanism == "Sigma-bond cleavage":
        return isinstance(precursor, str) and precursor.startswith("smiles_fragment:")

    if mechanism == "Dehydrogenation / Sequential dehydrogenation":
        return parse_precursor_mz(precursor) is not None

    return False


def should_avoid_neutral_loss_for_hydrocarbon(
    mechanism: str,
    product_ion: str,
    molecule_formula: str,
) -> bool:
    """
    For pure hydrocarbons, avoid using Neutral loss to explain simple hydrocarbon
    cation formation such as CH3+, C2H5+, or C3H7+.
    """
    if mechanism != "Neutral loss":
        return False

    product = parse_ion(product_ion)
    mol_counts = parse_formula_counts(molecule_formula)
    if product is None or not mol_counts:
        return False

    molecule_is_hydrocarbon = set(mol_counts.keys()).issubset({"C", "H"})
    product_is_hydrocarbon = set(product["counts"].keys()).issubset({"C", "H"})
    return molecule_is_hydrocarbon and product_is_hydrocarbon


def restore_supported_original_dehydrogenation(
    original_triplet: List[str],
    final_triplet: List[str],
    previous_reliable_precursor_triplets: List[List[str]],
) -> List[str]:
    """
    Prevent over-revision to a higher-hydrogen precursor.

    If the original triplet is already a valid same-carbon dehydrogenation step
    supported by reliable previous context, keep the original triplet even if the
    model or postprocessor changed it to a more saturated precursor.
    """
    original = normalize_triplet(original_triplet)
    final = normalize_triplet(final_triplet)
    if original is None or final is None:
        return final_triplet

    orig_precursor, orig_mechanism, orig_product = original
    if orig_mechanism != "Dehydrogenation / Sequential dehydrogenation":
        return final_triplet

    orig_mz = parse_precursor_mz(orig_precursor)
    product = parse_ion(orig_product)
    if orig_mz is None or product is None:
        return final_triplet

    previous_ions = find_previous_ions_by_mz(previous_reliable_precursor_triplets, orig_mz)
    original_is_supported = any(
        ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]
        for ion in previous_ions
    )

    if original_is_supported:
        return original

    return final_triplet


def get_original_precursor_status(
    triplet: List[str],
    previous_reliable_precursor_triplets: List[List[str]],
) -> Dict[str, Any]:
    normalized = normalize_triplet(triplet)
    if normalized is None:
        return {"is_supported": False}

    precursor, mechanism, product_ion = normalized
    product = parse_ion(product_ion)
    precursor_mz = parse_precursor_mz(precursor)

    if product is None or precursor_mz is None:
        return {
            "is_supported": False,
            "original_precursor_mz": precursor_mz,
            "mechanism": mechanism,
            "product_ion": product_ion,
            "supporting_previous_ions": [],
        }

    previous_ions = find_previous_ions_by_mz(previous_reliable_precursor_triplets, precursor_mz)
    supporting_previous_ions = [
        ion for ion in previous_ions
        if ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]
    ]

    return {
        "is_supported": len(supporting_previous_ions) > 0,
        "original_precursor_mz": precursor_mz,
        "mechanism": mechanism,
        "product_ion": product_ion,
        "supporting_previous_ions": supporting_previous_ions,
    }


# ============================================================
# 4. Context safety and fallback generation
# ============================================================

def is_context_safe_triplet(
    triplet: List[str],
    previous_verified_triplets: List[List[str]],
    smiles: str,
    molecule_formula: str,
) -> Tuple[bool, List[str]]:
    reasons: List[str] = []

    if not isinstance(triplet, list) or len(triplet) != 3:
        return False, ["Triplet is not a valid 3-element list."]

    precursor, mechanism, product_ion = triplet
    product = parse_ion(product_ion)

    if product is None:
        return False, ["Cannot parse product ion formula/mz."]

    if not product.get("has_unknown") and product.get("expected_mz", product["nominal_mass"]) != product["mz"]:
        reasons.append(
            f"Product ion formula/mz mismatch: formula={product['formula']}, "
            f"nominal_mass={product['nominal_mass']}, "
            f"isotope_annotation={product.get('isotope_annotation', '')}, "
            f"expected_mz={product.get('expected_mz', product['nominal_mass'])}, "
            f"mz={product['mz']}."
        )

    mol_counts = parse_formula_counts(molecule_formula)
    mol_c = mol_counts.get("C", 0)
    if mol_c > 0 and product["carbon"] > mol_c:
        reasons.append(
            f"Product ion carbon number C{product['carbon']} exceeds molecule carbon number C{mol_c}."
        )

    if should_avoid_sigma_for_unsaturated_product(mechanism, product_ion):
        reasons.append(
            "Plain Sigma-bond cleavage is not safe as context for a highly unsaturated "
            "hydrocarbon ion; prefer same-carbon dehydrogenation when available."
        )

    precursor_mz = parse_precursor_mz(precursor)

    if isinstance(precursor, str) and precursor.startswith("smiles_fragment:"):
        best_fragment, alternatives = parse_smiles_fragment_precursor(precursor)
        all_fragments = [best_fragment] + alternatives
        valid_fragments = [frag for frag in all_fragments if frag and frag in smiles]

        if not valid_fragments:
            reasons.append(f"No smiles_fragment candidate is a substring of source SMILES '{smiles}'.")
        else:
            if best_fragment not in valid_fragments:
                reasons.append(
                    f"Best smiles_fragment '{best_fragment}' is invalid, although valid alternatives exist: {valid_fragments}."
                )

            if best_fragment:
                frag_c = count_c_in_smiles(best_fragment)
                prod_c = product["carbon"]

                if prod_c > 0 and frag_c < prod_c:
                    reasons.append(
                        f"Best smiles_fragment carbon number C{frag_c} is smaller than product ion carbon number C{prod_c}."
                    )

                # For sigma-bond cleavage, an exact-carbon fragment is safer for context memory.
                if mechanism == "Sigma-bond cleavage" and prod_c > 0 and frag_c != prod_c:
                    reasons.append(
                        f"For Sigma-bond cleavage, best smiles_fragment carbon number C{frag_c} should match product ion carbon number C{prod_c} for safe context use."
                    )

    if precursor_mz is not None:
        previous_ions = find_previous_ions_by_mz(previous_verified_triplets, precursor_mz)

        # Treat the parent molecular ion as supported even if it has not yet appeared
        # in previous_verified_triplets. This fixes cases where an M+1 isotope
        # triplet appears before the molecular-ion triplet in the input order, e.g.
        # ["precursor_mz: 260", "Isotopic peak", "C20H20+ [M+1] (m/z 261)"].
        mol_counts_for_precursor = parse_formula_counts(molecule_formula)
        parent_nominal_mz = nominal_mass(mol_counts_for_precursor) if mol_counts_for_precursor else None
        parent_precursor_supported = (
            parent_nominal_mz is not None
            and precursor_mz == parent_nominal_mz
        )

        if not previous_ions and not parent_precursor_supported:
            reasons.append(f"precursor_mz:{precursor_mz} is not supported by previous verified corrected triplets.")

        if mechanism == "Dehydrogenation / Sequential dehydrogenation":
            same_carbon_higher_h_exists = any(
                prev_ion["carbon"] == product["carbon"]
                and prev_ion["hydrogen"] > product["hydrogen"]
                for prev_ion in previous_ions
            )

            if (
                not same_carbon_higher_h_exists
                and parent_precursor_supported
                and mol_counts_for_precursor
            ):
                same_carbon_higher_h_exists = (
                    mol_counts_for_precursor.get("C", 0) == product["carbon"]
                    and mol_counts_for_precursor.get("H", 0) > product["hydrogen"]
                )

            if previous_ions or parent_precursor_supported:
                if not same_carbon_higher_h_exists:
                    reasons.append(
                        "Invalid dehydrogenation: precursor and product do not preserve carbon number "
                        "or precursor does not have a higher hydrogen count."
                    )

        if mechanism == "Sigma-bond cleavage":
            reasons.append(
                "Sigma-bond cleavage with precursor_mz is not safe as sequential context; "
                "prefer structure-driven smiles_fragment for Sigma-bond cleavage."
            )

    return len(reasons) == 0, reasons


def sanitize_triplet(
    triplet: List[str],
    record: Dict[str, Any],
    previous_verified_triplets: List[List[str]],
) -> List[str]:
    """
    Lightweight deterministic cleanup:
    - If Sigma-bond cleavage uses an invalid/mismatched smiles_fragment, replace it
      with a valid exact-carbon fragment candidate.
    - If dehydrogenation uses an unsupported precursor_mz but a same-carbon higher-H
      previous precursor exists, replace the precursor_mz.
    """
    precursor, mechanism, product_ion = triplet
    smiles = record.get("smiles", "")
    product = parse_ion(product_ion)

    if product is None:
        return triplet

    # Avoid Neutral loss for simple hydrocarbon cation formation in pure hydrocarbons.
    if should_avoid_neutral_loss_for_hydrocarbon(
        mechanism=mechanism,
        product_ion=product_ion,
        molecule_formula=record.get("formula", ""),
    ):
        if is_alkyl_like_ion(product):
            return [precursor, "Sigma-bond cleavage", product_ion]
        return [precursor, "Dehydrogenation / Sequential dehydrogenation", product_ion]

    # Avoid plain Sigma-bond cleavage for highly unsaturated hydrocarbon ions
    # such as C2H3+, C3H5+, C3H3+, C4H7+, and C5H9+.
    if should_avoid_sigma_for_unsaturated_product(mechanism, product_ion):
        chosen_mz = choose_dehydrogenation_precursor(
            original_precursor=precursor,
            previous_verified_triplets=previous_verified_triplets,
            product_ion=product_ion,
        )
        if chosen_mz is not None:
            return [
                f"precursor_mz: {chosen_mz}",
                "Dehydrogenation / Sequential dehydrogenation",
                product_ion,
            ]

        # If no precursor_mz is available, keep the structure evidence but fix the mechanism.
        if isinstance(precursor, str) and precursor.startswith("smiles_fragment:"):
            return [
                precursor,
                "Dehydrogenation / Sequential dehydrogenation",
                product_ion,
            ]

        candidates = get_structure_fragment_candidates(smiles, product_ion)
        if candidates:
            return [
                format_smiles_fragment_candidate(candidates),
                "Dehydrogenation / Sequential dehydrogenation",
                product_ion,
            ]

    # Fix structure-driven sigma precursor if a better exact-carbon candidate exists.
    if isinstance(precursor, str) and precursor.startswith("smiles_fragment:"):
        candidates = get_structure_fragment_candidates(smiles, product_ion)
        best_fragment, _ = parse_smiles_fragment_precursor(precursor)
        best_c = count_c_in_smiles(best_fragment) if best_fragment else 0

        if candidates and (
            best_fragment not in smiles
            or best_c < product["carbon"]
            or (mechanism == "Sigma-bond cleavage" and best_c != product["carbon"])
        ):
            return [format_smiles_fragment_candidate(candidates), mechanism, product_ion]

    # Fix unsupported dehydrogenation precursor_mz.
    if mechanism == "Dehydrogenation / Sequential dehydrogenation":
        precursor_mz = parse_precursor_mz(precursor)
        prev_ions = find_previous_ions_by_mz(previous_verified_triplets, precursor_mz) if precursor_mz else []

        supported = any(
            ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]
            for ion in prev_ions
        )
        if not supported:
            chosen_mz = choose_dehydrogenation_precursor(
                original_precursor=precursor,
                previous_verified_triplets=previous_verified_triplets,
                product_ion=product_ion,
            )
            if chosen_mz is not None:
                return [
                    f"precursor_mz: {chosen_mz}",
                    "Dehydrogenation / Sequential dehydrogenation",
                    product_ion,
                ]

    return triplet


def fallback_corrected_triplet(
    record: Dict[str, Any],
    original_triplet: List[str],
    previous_verified_triplets: List[List[str]],
) -> List[str]:
    """
    Deterministic no-delete fallback. It always returns a non-empty 3-element triplet
    preserving the original product ion.
    """
    smiles = record.get("smiles", "")
    formula = record.get("formula", "")
    product_ion = original_triplet[2]
    product = parse_ion(product_ion)

    if product is None:
        # Keep original product string but force a structure-driven path.
        return [f"smiles_fragment: {smiles}", "Sigma-bond cleavage", product_ion]

    mol_counts = parse_formula_counts(formula)
    if mol_counts and product["counts"] == mol_counts:
        return [f"smiles_fragment: {smiles}", "Molecular ion", product_ion]

    # Same-carbon higher-H precursor from verified context.
    chosen_mz = choose_dehydrogenation_precursor(
        original_precursor=original_triplet[0],
        previous_verified_triplets=previous_verified_triplets,
        product_ion=product_ion,
    )
    if chosen_mz is not None:
        return [
            f"precursor_mz: {chosen_mz}",
            "Dehydrogenation / Sequential dehydrogenation",
            product_ion,
        ]

    # Structure-driven candidate with exact carbon count.
    frag_cands = get_structure_fragment_candidates(smiles, product_ion)
    if frag_cands:
        precursor = format_smiles_fragment_candidate(frag_cands)
        if is_alkyl_like_ion(product):
            mechanism = "Sigma-bond cleavage"
        elif is_unsaturated_hydrocarbon_ion(product):
            mechanism = "Dehydrogenation / Sequential dehydrogenation"
        else:
            mechanism = "Sigma-bond cleavage"
        return [precursor, mechanism, product_ion]

    # Last-resort: full molecule as a structure-driven precursor.
    mechanism = "Sigma-bond cleavage"
    if is_unsaturated_hydrocarbon_ion(product):
        mechanism = "Dehydrogenation / Sequential dehydrogenation"

    return [f"smiles_fragment: {smiles}", mechanism, product_ion]


def make_fallback_judge_output(
    record: Dict[str, Any],
    original_triplet: List[str],
    previous_verified_triplets: List[List[str]],
    reason_prefix: str,
) -> Dict[str, Any]:
    corrected = fallback_corrected_triplet(record, original_triplet, previous_verified_triplets)
    corrected = sanitize_triplet(corrected, record, previous_verified_triplets)

    return {
        "id": record.get("id", None),
        "name": record.get("name", ""),
        "smiles": record.get("smiles", ""),
        "formula": record.get("formula", ""),
        "mw": record.get("mw", ""),
        "original_triplet": original_triplet,
        "verdict": "revise",
        "reason": "",
        "corrected_triplet": corrected,
        "overall_quality": "Automatically revised by no-delete fallback after invalid or forbidden judge output.",
        "major_errors": ["Model output was invalid, empty, or used forbidden delete verdict."],
        "recommended_strategy": "Use the fallback corrected_triplet and inspect chemical_warnings/context_safe for downstream filtering."
    }


# ============================================================
# 5. API / JSON utilities
# ============================================================

def extract_json_from_text(text: str) -> Dict[str, Any]:
    if text is None:
        raise ValueError("Empty response content.")

    raw = text.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.IGNORECASE)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass

    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        candidate = raw[start:end + 1]
        return json.loads(candidate)

    raise ValueError(f"Cannot parse JSON from response:\n{raw[:1000]}")


def ensure_reason_field(parsed: Dict[str, Any]) -> Dict[str, Any]:
    """
    Keep the reason field in the saved JSON schema.

    If the model provides a reason, preserve it exactly as generated by the model.
    If the model omits it, set it to an empty string instead of generating a
    fixed rule-based explanation in code.
    """
    if isinstance(parsed, dict) and "reason" not in parsed:
        parsed["reason"] = ""
    return parsed


def validate_judge_output(parsed: Dict[str, Any]) -> List[str]:
    warnings: List[str] = []
    required_keys = [
        "id", "name", "smiles", "formula", "mw",
        "original_triplet", "verdict", "reason", "corrected_triplet",
        "overall_quality", "major_errors", "recommended_strategy",
    ]

    for key in required_keys:
        if key not in parsed:
            warnings.append(f"Missing key: {key}")

    verdict = parsed.get("verdict")
    if verdict not in ["accept", "revise"]:
        warnings.append(f"Invalid or forbidden verdict: {verdict}")

    if normalize_triplet(parsed.get("original_triplet")) is None:
        warnings.append("original_triplet is not a valid 3-element list.")

    if normalize_triplet(parsed.get("corrected_triplet")) is None:
        warnings.append("corrected_triplet must be a non-empty valid 3-element list.")

    if not isinstance(parsed.get("major_errors"), list):
        warnings.append("major_errors is not a list.")

    # Product ion should normally be preserved.
    original = normalize_triplet(parsed.get("original_triplet"))
    corrected = normalize_triplet(parsed.get("corrected_triplet"))
    if original is not None and corrected is not None and original[2] != corrected[2]:
        warnings.append("corrected_triplet changed the target product ion.")

    return warnings


def normalize_revise_without_change(parsed: Dict[str, Any]) -> Dict[str, Any]:
    """
    If the model says verdict=revise but corrected_triplet is identical to
    original_triplet, normalize the verdict to accept. This avoids inflated revise
    statistics without changing the final triplet.

    The model-generated reason is preserved as-is; no fixed reason sentence is appended by code.
    """
    if not isinstance(parsed, dict):
        return parsed

    original = normalize_triplet(parsed.get("original_triplet"))
    corrected = normalize_triplet(parsed.get("corrected_triplet"))

    if parsed.get("verdict") == "revise" and original is not None and corrected == original:
        parsed["verdict"] = "accept"

        major_errors = parsed.get("major_errors", [])
        if isinstance(major_errors, list) and not major_errors:
            parsed["overall_quality"] = parsed.get(
                "overall_quality",
                "Chemically reasonable; normalized to accept because no actual triplet change was made.",
            )

    return parsed


def enforce_current_record_metadata(
    parsed: Dict[str, Any],
    record: Dict[str, Any],
    original_triplet: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """
    Force saved metadata to match the current input molecule.

    This prevents the model from accidentally returning a renumbered id such as 1, 2, 3...
    when the current molecule actually has an original dataset id such as 75, 76, ...
    """
    if not isinstance(parsed, dict):
        return parsed

    parsed["id"] = record.get("id", None)
    parsed["name"] = record.get("name", "")
    parsed["smiles"] = record.get("smiles", "")
    parsed["formula"] = record.get("formula", "")
    parsed["mw"] = record.get("mw", "")

    if original_triplet is not None:
        parsed["original_triplet"] = original_triplet

    return parsed


def has_hard_format_error(warnings: List[str]) -> bool:
    hard_patterns = [
        "Missing key",
        "Invalid or forbidden verdict",
        "corrected_triplet must be a non-empty valid 3-element list",
        "original_triplet is not a valid 3-element list",
        "corrected_triplet changed the target product ion",
    ]
    return any(any(pattern in warning for pattern in hard_patterns) for warning in warnings)


def build_user_prompt(
    record: Dict[str, Any],
    triplet: List[str],
    triplet_index: int,
    previous_verified_corrected_triplets: List[List[str]],
    previous_reliable_precursor_triplets: List[List[str]],
) -> str:
    product_ion = triplet[2]
    payload = {
        "id": record.get("id", None),
        "name": record.get("name", ""),
        "smiles": record.get("smiles", ""),
        "formula": record.get("formula", ""),
        "mw": record.get("mw", ""),
        "triplet_index": triplet_index,
        "original_triplet": triplet,

        "all_original_triplets_for_this_molecule": record.get("triplets", []),
        "previous_verified_corrected_triplets_for_this_molecule": previous_verified_corrected_triplets,
        "previous_reliable_precursor_triplets_for_this_molecule": previous_reliable_precursor_triplets,
        "original_precursor_status": get_original_precursor_status(
            triplet,
            previous_reliable_precursor_triplets,
        ),

        # New model-facing hints.
        "same_carbon_higher_h_precursor_candidates": get_same_carbon_higher_h_precursor_candidates(
            previous_reliable_precursor_triplets,
            product_ion,
        ),
        "structure_fragment_candidates_for_product": get_structure_fragment_candidates(
            record.get("smiles", ""),
            product_ion,
        ),
    }

    if "compound_class" in record:
        payload["compound_class"] = record.get("compound_class")
    if "spectrum" in record:
        payload["spectrum"] = record.get("spectrum")
    if "input_spectrum" in record:
        payload["input_spectrum"] = record.get("input_spectrum")

    return (
        "Please judge the following existing EI-MS fragmentation triplet.\n"
        "You must output only verdict='accept' or verdict='revise'. The verdict 'delete' is forbidden.\n"
        "You must always provide a non-empty corrected_triplet.\n"
        "If the original precursor/mechanism is wrong, revise it so that the same target product ion is generated.\n"
        "Use same_carbon_higher_h_precursor_candidates for sequential dehydrogenation when possible, "
        "but do not replace an already valid original precursor_mz merely because a higher-H precursor also exists.\n"
        "Use structure_fragment_candidates_for_product for structure-driven Sigma-bond cleavage when possible.\n"
        "For Sigma-bond cleavage, prefer a structure-driven smiles_fragment over precursor_mz.\n"
        "Do not assume any future triplet has already been corrected.\n"
        "Return strict JSON only according to the system prompt.\n\n"
        "[Triplet judgment input]\n"
        f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
    )


def call_api_once(
    client: OpenAI,
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
    max_tokens: int,
    use_json_mode: bool = False,
) -> str:
    """
    Official OpenAI API call using the Responses API.

    The command-line argument is still named max_tokens to keep all existing
    retry logic and commands unchanged; it is mapped to max_output_tokens here.
    """
    kwargs = {
        "model": model,
        "input": messages,
        "temperature": temperature,
        "max_output_tokens": max_tokens,
    }

    # Optional JSON mode for the official Responses API.
    # If unsupported in your environment, the existing retry logic will retry without it.
    if use_json_mode:
        kwargs["text"] = {"format": {"type": "json_object"}}

    response = client.responses.create(**kwargs)

    if hasattr(response, "output_text") and response.output_text:
        return response.output_text

    parts = []
    for item in getattr(response, "output", []) or []:
        for content in getattr(item, "content", []) or []:
            text = getattr(content, "text", None)
            if text:
                parts.append(text)

    if parts:
        return "\n".join(parts)

    return str(response)


def call_api_with_token_retry(
    client: OpenAI,
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
    use_json_mode: bool,
) -> Tuple[Optional[Dict[str, Any]], str, Optional[str]]:
    token_attempts = [2048, 4096, 8192]
    raw_text = ""
    last_error = None

    for attempt, current_max_tokens in enumerate(token_attempts, start=1):
        try:
            print(f"[Token Attempt {attempt}/{len(token_attempts)}] max_tokens={current_max_tokens}")
            raw_text = call_api_once(
                client=client,
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=current_max_tokens,
                use_json_mode=use_json_mode,
            )
            parsed = extract_json_from_text(raw_text)
            return parsed, raw_text, None

        except Exception as e:
            last_error = str(e)
            print(
                f"[Token Attempt {attempt}/{len(token_attempts)}] "
                f"API or JSON parsing failed with max_tokens={current_max_tokens}: {last_error}"
            )

            if use_json_mode and ("response_format" in last_error or "json" in last_error.lower()):
                try:
                    print(f"[Fallback without json mode] max_tokens={current_max_tokens}")
                    raw_text = call_api_once(
                        client=client,
                        model=model,
                        messages=messages,
                        temperature=temperature,
                        max_tokens=current_max_tokens,
                        use_json_mode=False,
                    )
                    parsed = extract_json_from_text(raw_text)
                    return parsed, raw_text, None
                except Exception as e2:
                    last_error = str(e2)
                    print(f"[Fallback without json mode failed] {last_error}")

            if attempt < len(token_attempts):
                time.sleep(3)

    return None, raw_text, last_error


def semantic_retry_if_needed(
    client: OpenAI,
    model: str,
    messages: List[Dict[str, str]],
    parsed: Optional[Dict[str, Any]],
    raw_text: str,
    temperature: float,
    use_json_mode: bool,
    max_retries: int,
) -> Tuple[Optional[Dict[str, Any]], str, List[str], bool]:
    """
    Retry when the model violates the no-delete / non-empty corrected_triplet schema.
    """
    if parsed is None:
        return parsed, raw_text, ["Initial parsed output is None."], False

    warnings = validate_judge_output(parsed)
    if not has_hard_format_error(warnings):
        return parsed, raw_text, warnings, False

    current_parsed = parsed
    current_raw = raw_text
    current_warnings = warnings

    for retry_idx in range(1, max_retries + 1):
        print(f"[Semantic Retry {retry_idx}/{max_retries}] hard warnings: {current_warnings}")

        retry_messages = messages + [
            {"role": "assistant", "content": current_raw},
            {
                "role": "user",
                "content": (
                    "Your previous JSON violates the required no-delete schema. "
                    "You must output strict JSON only. "
                    "verdict must be only 'accept' or 'revise'. "
                    "The verdict 'delete' is forbidden. "
                    "corrected_triplet must be a non-empty 3-element list. "
                    "Preserve the same target product ion as the original_triplet. "
                    "If the original precursor or mechanism is wrong, revise it using a valid "
                    "previous precursor candidate or a structure-driven smiles_fragment."
                ),
            },
        ]

        retry_parsed, retry_raw, retry_error = call_api_with_token_retry(
            client=client,
            model=model,
            messages=retry_messages,
            temperature=temperature,
            use_json_mode=use_json_mode,
        )

        if retry_parsed is None:
            current_warnings = [f"Semantic retry failed: {retry_error}"]
            continue

        retry_warnings = validate_judge_output(retry_parsed)
        current_parsed = retry_parsed
        current_raw = retry_raw
        current_warnings = retry_warnings

        if not has_hard_format_error(retry_warnings):
            return current_parsed, current_raw, current_warnings, True

    return current_parsed, current_raw, current_warnings, True


# ============================================================
# 6. Corrected output extraction
# ============================================================

def build_corrected_outputs(
    input_records: List[Dict[str, Any]],
    full_results: List[Dict[str, Any]],
    include_unsafe_in_corrected: bool = False,
) -> List[Dict[str, Any]]:
    grouped: Dict[Any, Dict[str, Any]] = {}

    for record in input_records:
        data_id = record.get("id", None)
        grouped[data_id] = {
            "id": data_id,
            "name": record.get("name", ""),
            "smiles": record.get("smiles", ""),
            "formula": record.get("formula", ""),
            "mw": record.get("mw", ""),
            "corrected_triplet": [],
        }

    for item in full_results:
        data_id = item.get("id", None)
        if data_id not in grouped:
            grouped[data_id] = {
                "id": data_id,
                "name": item.get("name", ""),
                "smiles": item.get("smiles", ""),
                "formula": item.get("formula", ""),
                "mw": item.get("mw", ""),
                "corrected_triplet": [],
            }

        final_triplet = normalize_triplet(item.get("final_corrected_triplet"))

        # No-delete output policy:
        # context_safe only controls whether a triplet can be reused as later context.
        # It must not filter the final corrected_output_file, otherwise unsafe triplets
        # would be silently removed and behave like delete.
        if final_triplet is not None:
            grouped[data_id]["corrected_triplet"].append(final_triplet)

    return list(grouped.values())


# ============================================================
# 7. Main process
# ============================================================

def filter_records(records: List[Dict[str, Any]], args: argparse.Namespace) -> List[Dict[str, Any]]:
    selected = []
    for record in records:
        rid = record.get("id", None)
        if args.id_min is not None and isinstance(rid, int) and rid < args.id_min:
            continue
        if args.id_max is not None and isinstance(rid, int) and rid > args.id_max:
            continue
        selected.append(record)

    if args.limit is None:
        return selected[args.start:]
    return selected[args.start:args.start + args.limit]


def main() -> None:
    args = parse_args()

    api_key = args.api_key or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("API key is missing. Please pass --api_key or set OPENAI_API_KEY.")

    # Official OpenAI API client. Do not pass base_url.
    # args.base_url is intentionally ignored and kept only for old command compatibility.
    client = OpenAI(api_key=api_key)

    records = load_json(args.input_file)
    if isinstance(records, dict):
        records = [records]
    if not isinstance(records, list):
        raise ValueError("Input JSON must be a list or a single dict.")

    selected_records = filter_records(records, args)

    full_results: List[Dict[str, Any]] = []
    processed_keys = set()
    existing_by_key: Dict[Tuple[Any, Any], Dict[str, Any]] = {}

    if args.skip_existing and os.path.exists(args.output_file):
        try:
            full_results = load_json(args.output_file)
            for item in full_results:
                key = (item.get("id"), item.get("triplet_index"))
                processed_keys.add(key)
                existing_by_key[key] = item
            print(f"Loaded {len(full_results)} existing judge results.")
        except Exception as e:
            print(f"Failed to load existing output file. Start from empty results. Error: {e}")
            full_results = []
            processed_keys = set()
            existing_by_key = {}

    total_triplets = sum(len(r.get("triplets", [])) for r in selected_records if isinstance(r, dict))

    print("=" * 80)
    print(f"Total selected molecules: {len(selected_records)}")
    print(f"Total triplets to judge: {total_triplets}")
    print(f"id_min={args.id_min}, id_max={args.id_max}, start={args.start}, limit={args.limit}")
    print(f"Model: {args.model}")
    print("API: OpenAI official Responses API")
    print(f"Full output file: {args.output_file}")
    print(f"Corrected output file: {args.corrected_output_file}")
    print(f"include_unsafe_in_corrected: {args.include_unsafe_in_corrected}")
    print("=" * 80)

    judged_count = 0

    for record_idx, record in enumerate(selected_records, start=1):
        if not isinstance(record, dict):
            continue

        data_id = record.get("id", None)
        name = record.get("name", "")
        smiles = record.get("smiles", "")
        formula = record.get("formula", "")
        mw = record.get("mw", "")
        triplets = record.get("triplets", [])

        previous_verified_corrected_triplets: List[List[str]] = []
        previous_reliable_precursor_triplets: List[List[str]] = []

        if not isinstance(triplets, list):
            print(f"[Skip] id={data_id}: triplets is not a list.")
            continue

        print("=" * 80)
        print(
            f"[Molecule {record_idx}/{len(selected_records)}] "
            f"id={data_id}, name={name}, smiles={smiles}, formula={formula}, mw={mw}, "
            f"triplets={len(triplets)}"
        )

        for triplet_index, triplet in enumerate(triplets):
            normalized_triplet = normalize_triplet(triplet)

            previous_before_current = previous_verified_corrected_triplets[:]
            previous_reliable_before_current = previous_reliable_precursor_triplets[:]

            if normalized_triplet is None:
                fallback = fallback_corrected_triplet(
                    record=record,
                    original_triplet=["", "Sigma-bond cleavage", ""],
                    previous_verified_triplets=previous_verified_corrected_triplets,
                )
                result_item = {
                    "id": data_id,
                    "name": name,
                    "smiles": smiles,
                    "formula": formula,
                    "mw": mw,
                    "triplet_index": triplet_index,
                    "original_triplet": triplet,
                    "judge_output": None,
                    "model_judge_output_before_fallback": None,
                    "final_corrected_triplet": fallback,
                    "auto_fallback_used": True,
                    "raw_response": "",
                    "parse_ok": False,
                    "error": "Invalid input triplet format; expected a 3-element list.",
                    "warnings": ["Invalid input triplet format."],
                    "chemical_warnings": ["Invalid input triplet format."],
                    "context_safe": False,
                    "context_reliable_for_precursor": False,
                    "triplet_postprocess_modified": False,
                    "verdict_postprocess_modified": False,
                    "previous_verified_corrected_triplets_before_current": previous_before_current,
                    "previous_reliable_precursor_triplets_before_current": previous_reliable_before_current,
                }
                full_results.append(result_item)
                continue

            key = (data_id, triplet_index)
            if args.skip_existing and key in processed_keys:
                print(f"[Skip existing] id={data_id}, triplet_index={triplet_index}")
                existing_item = existing_by_key.get(key)
                if existing_item:
                    final_triplet = normalize_triplet(existing_item.get("final_corrected_triplet"))
                    if final_triplet is not None and existing_item.get("context_safe", False):
                        previous_verified_corrected_triplets.append(final_triplet)
                        if existing_item.get("context_reliable_for_precursor", False) or is_reliable_for_precursor_context(final_triplet):
                            previous_reliable_precursor_triplets.append(final_triplet)
                continue

            judged_count += 1
            print("-" * 80)
            print(
                f"[Judge {judged_count}/{total_triplets}] "
                f"id={data_id}, triplet_index={triplet_index}, triplet={normalized_triplet}"
            )
            print(f"Previous verified corrected triplets available: {len(previous_verified_corrected_triplets)}")

            user_prompt = build_user_prompt(
                record=record,
                triplet=normalized_triplet,
                triplet_index=triplet_index,
                previous_verified_corrected_triplets=previous_before_current,
                previous_reliable_precursor_triplets=previous_reliable_before_current,
            )
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ]

            parsed, raw_text, error = call_api_with_token_retry(
                client=client,
                model=args.model,
                messages=messages,
                temperature=args.temperature,
                use_json_mode=args.use_json_mode,
            )

            model_judge_output_before_fallback = None
            parse_ok = parsed is not None
            semantic_retry_used = False

            if parsed is not None:
                parsed, raw_text, warnings, semantic_retry_used = semantic_retry_if_needed(
                    client=client,
                    model=args.model,
                    messages=messages,
                    parsed=parsed,
                    raw_text=raw_text,
                    temperature=args.temperature,
                    use_json_mode=args.use_json_mode,
                    max_retries=args.semantic_retry,
                )
                if parsed is not None:
                    parsed = enforce_current_record_metadata(
                        parsed=parsed,
                        record=record,
                        original_triplet=normalized_triplet,
                    )
                    parsed = ensure_reason_field(parsed)
                    model_judge_output_before_fallback = copy.deepcopy(parsed)
                    original_model_verdict = parsed.get("verdict")
                    original_model_corrected = normalize_triplet(parsed.get("corrected_triplet"))
                    parsed = normalize_revise_without_change(parsed)
                    parsed = enforce_current_record_metadata(
                        parsed=parsed,
                        record=record,
                        original_triplet=normalized_triplet,
                    )
                    parsed = ensure_reason_field(parsed)
                    warnings = validate_judge_output(parsed)
                else:
                    original_model_verdict = None
                    original_model_corrected = None
            else:
                original_model_verdict = None
                original_model_corrected = None
                warnings = [error or "API/JSON parsing failed."]

            auto_fallback_used = False

            if parsed is None or has_hard_format_error(warnings):
                parsed = make_fallback_judge_output(
                    record=record,
                    original_triplet=normalized_triplet,
                    previous_verified_triplets=previous_verified_corrected_triplets,
                    reason_prefix="The API output was missing, invalid, or still used a forbidden delete/empty corrected_triplet after retry."
                )
                parsed = enforce_current_record_metadata(
                    parsed=parsed,
                    record=record,
                    original_triplet=normalized_triplet,
                )
                parsed = ensure_reason_field(parsed)
                warnings = validate_judge_output(parsed)
                auto_fallback_used = True

            # Final corrected triplet used for final output and context.
            final_corrected = normalize_triplet(parsed.get("corrected_triplet"))
            if final_corrected is None:
                final_corrected = fallback_corrected_triplet(
                    record=record,
                    original_triplet=normalized_triplet,
                    previous_verified_triplets=previous_verified_corrected_triplets,
                )
                auto_fallback_used = True

            model_corrected_before_postprocess = normalize_triplet(parsed.get("corrected_triplet"))

            final_corrected = sanitize_triplet(
                triplet=final_corrected,
                record=record,
                previous_verified_triplets=previous_reliable_precursor_triplets,
            )

            final_corrected = restore_supported_original_dehydrogenation(
                original_triplet=normalized_triplet,
                final_triplet=final_corrected,
                previous_reliable_precursor_triplets=previous_reliable_precursor_triplets,
            )

            triplet_postprocess_modified = (
                model_corrected_before_postprocess is not None
                and final_corrected != model_corrected_before_postprocess
            )
            verdict_postprocess_modified = (
                original_model_verdict is not None
                and parsed is not None
                and original_model_verdict != parsed.get("verdict")
            )
            postprocess_modified = triplet_postprocess_modified or verdict_postprocess_modified

            context_safe, chemical_warnings = is_context_safe_triplet(
                triplet=final_corrected,
                previous_verified_triplets=previous_reliable_precursor_triplets,
                smiles=smiles,
                molecule_formula=formula,
            )

            context_reliable_for_precursor = context_safe and is_reliable_for_precursor_context(final_corrected)

            if context_safe:
                previous_verified_corrected_triplets.append(final_corrected)
                if context_reliable_for_precursor:
                    previous_reliable_precursor_triplets.append(final_corrected)

            result_item = {
                "id": data_id,
                "name": name,
                "smiles": smiles,
                "formula": formula,
                "mw": mw,
                "triplet_index": triplet_index,
                "original_triplet": normalized_triplet,
                "judge_output": parsed,
                "model_judge_output_before_fallback": model_judge_output_before_fallback,
                "final_corrected_triplet": final_corrected,
                "auto_fallback_used": auto_fallback_used,
                "semantic_retry_used": semantic_retry_used,
                "postprocess_modified": postprocess_modified,
                "triplet_postprocess_modified": triplet_postprocess_modified,
                "verdict_postprocess_modified": verdict_postprocess_modified,
                "context_reliable_for_precursor": context_reliable_for_precursor,
                "raw_response": raw_text,
                "parse_ok": parse_ok,
                "error": None if parse_ok else error,
                "warnings": warnings,
                "chemical_warnings": chemical_warnings,
                "context_safe": context_safe,
                "previous_verified_corrected_triplets_before_current": previous_before_current,
                "previous_reliable_precursor_triplets_before_current": previous_reliable_before_current,
            }

            full_results.append(result_item)

            print(
                f"Success. verdict={parsed.get('verdict')} "
                f"warnings={len(warnings)} "
                f"chemical_warnings={len(chemical_warnings)} "
                f"context_safe={context_safe} "
                f"context_reliable_for_precursor={context_reliable_for_precursor} "
                f"auto_fallback_used={auto_fallback_used} "
                f"previous_verified_corrected_triplets={len(previous_verified_corrected_triplets)} "
                f"previous_reliable_precursor_triplets={len(previous_reliable_precursor_triplets)}"
            )
            if warnings:
                for w in warnings[:10]:
                    print(f"  [Warning] {w}")
            if chemical_warnings:
                for w in chemical_warnings[:10]:
                    print(f"  [Chemical Warning] {w}")

            if args.save_every > 0 and len(full_results) % args.save_every == 0:
                save_json(full_results, args.output_file)
                corrected_outputs = build_corrected_outputs(
                    input_records=selected_records,
                    full_results=full_results,
                    include_unsafe_in_corrected=args.include_unsafe_in_corrected,
                )
                save_json(corrected_outputs, args.corrected_output_file)
                print(f"Intermediate full results saved to: {args.output_file}")
                print(f"Intermediate corrected results saved to: {args.corrected_output_file}")

            if args.sleep > 0:
                time.sleep(args.sleep)

    save_json(full_results, args.output_file)
    corrected_outputs = build_corrected_outputs(
        input_records=selected_records,
        full_results=full_results,
        include_unsafe_in_corrected=args.include_unsafe_in_corrected,
    )
    save_json(corrected_outputs, args.corrected_output_file)

    print("=" * 80)
    print("All done.")
    print(f"Saved full judge results: {args.output_file}")
    print(f"Saved corrected triplets: {args.corrected_output_file}")


if __name__ == "__main__":
    main()
