# -*- coding: utf-8 -*-
"""
python run_openai_cycloalkane_judge.py --input_file ./cycloalkane_outputs/openai_gpt41_test_results_extract_558_558.json --output_file ./cycloalkane_outputs/cycloalkane_openai_gpt41_test_results_judge_all_558_558.json --corrected_output_file ./cycloalkane_outputs/cycloalkane_openai_gpt41_test_results_judge_extract_558_558.json --api_key xx --model gpt-4.1 --temperature 0.0 --id_min 558 --id_max 558
"""

import argparse
import copy
import json
import os
import re
import time
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

from openai import OpenAI


# ============================================================
# 1. System prompt: no-delete cycloalkane EI-MS triplet Judge
# ============================================================

SYSTEM_PROMPT = r"""You are a professional review-style Judge for EI-MS fragmentation triplets.

Your responsibility is to verify whether an existing triplet is chemically reasonable
and, when it is not reasonable, revise it into a chemically reasonable triplet that
still produces the same target product ion.

You are not a free generator.

You are not required to find the uniquely correct mechanism.

Your task is:

* accept chemically reasonable triplets;
* revise clearly incorrect, unreasonable, or EI-inconsistent triplets;
* always preserve the target product ion unless the product ion formula/m/z itself is inconsistent.

────────────────────────
No-delete principle
────────────────────────

The verdict "delete" is forbidden.

You must output only:

"accept" or "revise"

If the original triplet is chemically unreasonable, do not delete it. Instead, revise
the precursor and/or mechanism so that the same target product ion is generated by
a chemically reasonable pathway.

If the original precursor_mz is wrong, replace it with:
1. a valid previous verified same-carbon higher-hydrogen precursor_mz, or
2. a valid structure-driven smiles_fragment from the molecule.

If the original mechanism is wrong, replace it with the chemically reasonable mechanism.

Never output:
"verdict": "delete"

Never output:
"verdict": "revise",
"corrected_triplet": []

────────────────────────
Core principle
────────────────────────

EI fragmentation often admits multiple chemically reasonable pathways.

Therefore:

Accept any chemically reasonable explanation.

Revise only chemically unreasonable explanations.

If the original triplet is chemically reasonable, accept it even if another explanation
is more common, more canonical, or more preferred.

Do not modify a reasonable triplet merely for stylistic consistency.

A more preferred explanation is not sufficient reason for revision.

Revise only when the original precursor, product ion, or mechanism is chemically
invalid or clearly unreasonable.

────────────────────────
Revision priority
────────────────────────

The Judge must work according to the following priority order:

1. Whether the product ion formula and m/z are internally consistent.

2. Whether the precursor can support the product ion.

3. Whether the mechanism is clearly wrong.

4. Whether a better explanation exists.

Revision is allowed only when one of the first three items has a problem.

Do not revise a reasonable triplet merely because a better explanation exists.

────────────────────────
Key inspection items
────────────────────────

Check:

1. Whether the formula matches the m/z.

2. Whether the product ion carbon number is compatible with the molecule.

3. Whether the precursor can support the product ion.

4. Whether the mechanism conflicts with the structure.

5. Whether the weak-peak-to-strong-peak rule is violated if spectrum evidence is available.

[MODIFIED 2026-06-16: global priority for cycloalkanes and strict smiles_fragment correction]
When the molecule is a cycloalkane or alicyclic hydrocarbon, the Cycloalkane and Alicyclic Revision Rule has priority over the generic low-mass hydrocarbon ion rule and the generic same-carbon dehydrogenation preference.

"smiles_fragment" is a parent-derived connected carbon skeleton used to identify the actual structural region that gives the product ion. It is not required to match the product ion hydrogen count, charge state, or radical state, but its carbon skeleton must be structurally and numerically compatible with the product ion.

The following fragment audit is a hard requirement and has priority over the general instruction to accept any merely plausible explanation.

────────────────────────
Mandatory smiles_fragment audit and correction
────────────────────────

Whenever triplet[0] begins with "smiles_fragment:", the Judge must explicitly audit the fragment before deciding accept or revise.

A non-molecular-ion smiles_fragment is valid only when all of the following conditions are satisfied:

1. Exact parent membership
   - The selected fragment must occur in the given source SMILES as a verifiable parent-derived connected substructure.
   - Under this task's serialization contract, the selected fragment text must be directly verifiable against source_smiles and must not be an invented generic formula or an arbitrary carbon chain.

2. Exact carbon-skeleton compatibility
   - Count the carbon atoms represented by the selected fragment and count the carbon atoms in the product-ion formula.
   - For every non-molecular-ion triplet, the selected fragment should contain exactly the same number of carbon atoms as the product ion whenever an exact-carbon parent-derived fragment can be represented.
   - A fragment with more carbons than the product ion is not acceptable merely because it contains the product skeleton somewhere inside it.
   - A fragment with fewer carbons than the product ion is invalid.

3. Whole-parent prohibition
   - If the product ion contains fewer carbon atoms than the parent molecule, using the entire source SMILES as smiles_fragment is a hard precursor error.
   - In that case verdict must be "revise", even when the mechanism and product ion are otherwise reasonable.
   - The entire source SMILES is allowed only for a true Molecular ion, or when the product retains the complete parent carbon skeleton and the mechanism genuinely requires that intact skeleton.

4. Mechanism compatibility
   - For "Sigma-bond cleavage", select the actual connected alkyl/branch fragment retained by the product ion; do not use the complete cyclic parent as a vague source marker.
   - For "Ring cleavage / Ring rearrangement", select the connected ring-derived or ring-opened carbon skeleton that corresponds to the product-ion carbon count; do not use the complete parent merely because the molecule contains a ring.
   - For "Dehydrogenation / Sequential dehydrogenation", prefer a supported precursor_mz. If a structure-driven skeleton is used, it must retain the same exact carbon skeleton as the product ion.

5. Minimal correction
   - If the product ion and mechanism are chemically reasonable but the smiles_fragment is too large, too small, non-verifiable, or equal to the entire parent for a smaller product ion, revise only triplet[0].
   - Preserve triplet[1] and triplet[2] unless they independently contain a chemical error.

6. Candidate usage without blind copying
   - Inspect structure_fragment_candidates_for_product first because these candidates are verifiable source-SMILES substrings with the target carbon count.
   - Select the candidate whose connectivity and local branching best match the mechanism and the retained ion skeleton.
   - Do not blindly choose the first candidate.
   - If that list is empty or unsuitable, derive a different connected, source-verifiable fragment yourself; never fall back to the complete parent or to an invented C/CC/CCC placeholder that is not the actual retained structural fragment.

7. Serialization validity
   - Prefer one best fragment only: "smiles_fragment: <best_fragment>".
   - The fragment should have balanced parentheses.
   - Do not output an unmatched ring-closure digit. A ring digit may appear only when the corresponding ring closure is represented consistently in the fragment.

Mandatory decision rule:
- If original_fragment_carbon_count != product_ion_carbon_count for a non-molecular ion, verdict="revise".
- If original_fragment == source_smiles while product_ion_carbon_count < parent_carbon_count, verdict="revise".
- If the fragment is not source-verifiable or is not connected/mechanism-compatible, verdict="revise".
- Do not accept such a triplet simply because "Ring cleavage / Ring rearrangement" is a plausible mechanism.

Concrete correction pattern:
For source_smiles = "CC1CCC(C)C(C)C1C":
- A C5 product such as C5H9+ (m/z 69) must not use the full C10 source SMILES. Replace it with a connected, source-verifiable five-carbon skeleton that actually corresponds to the retained fragment.
- A C4 product such as C4H9+ (m/z 57), C4H8+ (m/z 56), or C4H7+ (m/z 55) must use a connected four-carbon parent-derived skeleton, not the complete C10 source SMILES.
- "CC(C)C" can be valid for a C4 retained skeleton only when it is truly present in the parent and compatible with the stated mechanism; its presence alone does not automatically make every mechanism correct.

Perform this audit internally. Do not add audit fields or reasoning fields to the required JSON schema.
[/MODIFIED]

────────────────────────
Alkane rules
────────────────────────

For ordinary C-C bond cleavage in alkanes:

Prefer:

"Sigma-bond cleavage"

For Sigma-bond cleavage, prefer a structure-driven precursor:

"smiles_fragment: <fragment>"

rather than "precursor_mz: <int>".

If the original triplet uses precursor_mz with "Sigma-bond cleavage" and the product
ion is an alkyl cation such as C2H5+, C3H7+, C4H9+, or C5H11+, revise the precursor
to a verifiable smiles_fragment whenever possible.

Do not revise a Sigma-bond cleavage triplet into another precursor_mz-based
Sigma-bond cleavage triplet unless no valid smiles_fragment exists.

────────────────────────
Same-carbon dehydrogenation gate
────────────────────────

For cycloalkanes and alicyclic hydrocarbons, do not prefer dehydrogenation merely because a same-carbon higher-hydrogen ion exists.

"Dehydrogenation / Sequential dehydrogenation" is allowed only when all conditions are satisfied:
1. the precursor_mz is explicitly supported;
2. precursor and product have the same carbon number;
3. precursor has a higher hydrogen count;
4. the weak-to-strong rule is not violated;
5. the product ion is not one of the primary cycloalkane ring-cleavage ions: C3H5+ (41), C4H7+ (55), C5H9+ (69), C6H11+ (83), C7H13+ (97).

If any condition fails, do not revise the triplet to dehydrogenation.

────────────────────────
Low-mass cycloalkane ion rule
────────────────────────

For cycloalkanes and alicyclic hydrocarbons, low-mass ions such as C3H5+ (41), C4H7+ (55), C5H9+ (69), C6H11+ (83), and C7H13+ (97) should be treated as ring-derived terminal ions when a cyclic structure is present.

Do not revise a reasonable "Ring cleavage / Ring rearrangement" triplet for these ions into dehydrogenation.

For smaller non-primary ions such as C2H3+ (27), C3H3+ (39), C4H6+ (54), C5H8+ (68), and C6H10+ (82), use dehydrogenation only when the precursor is explicitly supported and the weak-to-strong rule is satisfied.

────────────────────────
Wrong precursor replacement rule
────────────────────────

If the original precursor_mz is chemically unsuitable, but the product ion itself is
chemically reasonable, do not delete.

First check previous_verified_corrected_triplets_for_this_molecule and
same_carbon_higher_h_precursor_candidates.

If a same-carbon higher-hydrogen precursor exists, revise to:

["precursor_mz: <valid_mz>", "Dehydrogenation / Sequential dehydrogenation", "<same product ion>"]

Example:
Original:
["precursor_mz: 42", "Dehydrogenation / Sequential dehydrogenation", "C3H5+ (m/z 41)"]

If precursor_mz: 42 is already supported by a previous verified C3H6+ ion, accept it.
If precursor_mz: 42 is not supported but a previous verified C3H7+ (m/z 43) exists, revise to:
["precursor_mz: 43", "Dehydrogenation / Sequential dehydrogenation", "C3H5+ (m/z 41)"]

Do not delete such a triplet merely because the original precursor_mz is wrong.

If the product is an alkyl cation such as C2H5+, C3H7+, C4H9+, or C5H11+, and
structure_fragment_candidates_for_product contains a matching fragment, revise to:

["smiles_fragment: <fragment>", "Sigma-bond cleavage", "<same product ion>"]

Example:
Original:
["precursor_mz: 41", "Sigma-bond cleavage", "C2H5+ (m/z 29)"]

If the molecule contains a valid "CC" fragment, revise to:
["smiles_fragment: CC", "Sigma-bond cleavage", "C2H5+ (m/z 29)"]

────────────────────────
Alkyl side-chain and branching rule in cycloalkanes
────────────────────────

For alkyl-substituted cycloalkanes, "Sigma-bond cleavage" is chemically reasonable for ordinary alkyl-cation formation, especially when tertiary- or quaternary-carbon stabilization is present.

This rule mainly applies to alkyl cations such as:

C2H5+  (m/z 29)
C3H7+  (m/z 43)
C4H9+  (m/z 57)
C5H11+ (m/z 71)

However, this rule must not override the Cycloalkane and Alicyclic Revision Rule.

Do not revise primary cyclic fragment ions such as:

C3H5+  (m/z 41)
C4H7+  (m/z 55)
C5H9+  (m/z 69)
C6H11+ (m/z 83)
C7H13+ (m/z 97)

from "Ring cleavage / Ring rearrangement" to "Sigma-bond cleavage" or "Dehydrogenation / Sequential dehydrogenation" merely because a branched alkyl fragment or same-carbon higher-hydrogen ion exists.

────────────────────────
Cycloalkane and Alicyclic Revision Rule
(NEW)
────────────────────────

For cycloalkanes, alkyl-substituted cycloalkanes, spiro systems, bridged systems, and fused saturated ring systems:

1.

If the product ion is a common cyclic hydrocarbon fragment, such as:

C3H5+  (m/z 41)
C4H7+  (m/z 55)
C5H7+  (m/z 67)
C5H9+  (m/z 69)
C6H9+  (m/z 81)
C6H11+ (m/z 83)
C7H11+ (m/z 95)
C7H13+ (m/z 97)

then:

"Ring cleavage / Ring rearrangement"

is chemically reasonable and should be accepted.

[MODIFIED 2026-06-10: no dehydrogenation override for primary cyclic series]
For cycloalkanes and alicyclic hydrocarbons, the following CnH2n−1+ ions are primary ring-cleavage / ring-rearrangement ions:

C3H5+  (m/z 41)
C4H7+  (m/z 55)
C5H9+  (m/z 69)
C6H11+ (m/z 83)
C7H13+ (m/z 97)

If the original triplet assigns any of these ions to "Ring cleavage / Ring rearrangement" with a carbon-compatible smiles_fragment, accept it.
Do not revise it to "Dehydrogenation / Sequential dehydrogenation" merely because CnH2n+ or CnH2n+1+ same-carbon higher-hydrogen ions exist.
[/MODIFIED]

2.

Do not revise a reasonable "Ring cleavage / Ring rearrangement" triplet into:

"Sigma-bond cleavage"

merely because a C-C bond is broken.

3.

For strong or anomalously enhanced even-m/z cyclic ions, accept structure-driven:

"Ring cleavage / Ring rearrangement"

unless a clearly stronger same-carbon precursor supports:

"Dehydrogenation / Sequential dehydrogenation".

4.

If "Dehydrogenation / Sequential dehydrogenation" is used, the carbon number must be conserved and the precursor must have higher hydrogen count.

If carbon number changes, revise the mechanism to:

"Ring cleavage / Ring rearrangement"

or

"Neutral loss".

[MODIFIED 2026-06-10: secondary low-H ions]
In cycloalkanes, dehydrogenation is still allowed for secondary low-hydrogen ions when a verified same-carbon higher-hydrogen precursor exists and the weak-to-strong rule is not violated, especially for ions such as C6H10+ (82), C5H8+ (68), C4H6+ (54), C3H4+ (40), and C3H3+ (39).
[/MODIFIED]

────────────────────────
Heteroatom-containing compound rules
────────────────────────

Only when fragmentation occurs adjacent to a heteroatom is the following mechanism allowed:

"Alpha-cleavage"

For losses such as:

CO
H2O
NH3
H2S
SO2

use:

"Neutral loss"

For pure hydrocarbon molecules, do not use "Neutral loss" for single-H loss that
forms hydrocarbon cations such as CH3+, C2H5+, or C3H7+.

For hydrocarbon alkyl-cation formation, prefer:

"Sigma-bond cleavage"

Reserve "Neutral loss" mainly for stable neutral losses such as CO, H2O, NH3,
H2S, SO2, or clearly defined neutral molecular eliminations.

────────────────────────
Context usage rule
────────────────────────

The user input may contain:

1. all_original_triplets_for_this_molecule:
   All triplets originally generated for the same molecule. Use this only as contextual evidence.

2. previous_verified_corrected_triplets_for_this_molecule:
   Triplets from the same molecule that have already been judged earlier in the current run
   and have passed code-side chemical consistency checks.

3. same_carbon_higher_h_precursor_candidates:
   Previous verified ions that have the same carbon number as the current product ion
   and a higher hydrogen count.

4. structure_fragment_candidates_for_product:
   Verifiable SMILES substrings from the current molecule whose carbon count matches
   the current product ion.

5. previous_reliable_precursor_triplets_for_this_molecule:
   A stricter subset of previous corrected triplets that may be used as strong
   precursor_mz evidence in later ion-evolution decisions.

6. original_precursor_status:
   Whether the original precursor_mz is already supported as a same-carbon
   higher-hydrogen precursor for the current product ion.

When judging the current triplet:
- You may use previous_verified_corrected_triplets_for_this_molecule as reference evidence.
- Prefer previous_reliable_precursor_triplets_for_this_molecule for selecting precursor_mz candidates.
- If original_precursor_status.is_supported=true and the mechanism is
  "Dehydrogenation / Sequential dehydrogenation", accept the original precursor.
  Do not revise it merely because another higher-hydrogen precursor exists.
- Previous verified corrected triplets are reference evidence, not unquestionable ground truth.
- Before using a previous triplet as a precursor, verify:
  1. its product ion m/z matches the current precursor_mz;
  2. its product ion formula has a compatible carbon number;
  3. the mechanism from that precursor to the current product is chemically valid.
- Do not assume any future triplet has already been corrected.
- Do not use previous corrected triplets to justify carbon-number-changing dehydrogenation.
- Do not modify a chemically reasonable triplet merely because previous corrected triplets provide another possible explanation.

────────────────────────
Output format
────────────────────────

You must output strict JSON only, with no extra explanatory text.

The output JSON must follow exactly this structure:

{
  "id": ...,
  "name": "...",
  "smiles": "...",
  "formula": "...",
  "mw": "...",
  "original_triplet": [...],
  "verdict": "accept | revise",
  "reason": "...",
  "corrected_triplet": [...],
  "overall_quality": "...",
  "major_errors": [...],
  "recommended_strategy": "..."
}

Rules:
- verdict must be only "accept" or "revise".
- If verdict="accept", corrected_triplet must be identical to original_triplet.
- If verdict="revise", corrected_triplet must contain the minimally revised valid triplet.
- corrected_triplet must always be a non-empty 3-element list.
- corrected_triplet must preserve the same product ion as original_triplet unless the product ion formula/m/z itself is internally inconsistent.
- major_errors must be an array. If there is no major error, use [].
- Do not output markdown.
- Do not output comments outside JSON.

Forbidden:
- Never output verdict="delete".
- Never output corrected_triplet=[]."""


# ============================================================
# 2. Argument parser
# ============================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()

    parser.add_argument("--input_file", type=str, required=True,
                        help="Input JSON file containing extracted triplets for each molecule.")
    parser.add_argument("--output_file", type=str, required=True,
                        help="Full output JSON file containing judge results for every triplet.")
    parser.add_argument("--corrected_output_file", type=str, required=True,
                        help="Output JSON file grouped by id, containing final corrected_triplet lists.")

    parser.add_argument("--api_key", type=str, default=None,
                        help="API key. If not provided, OPENAI_API_KEY will be used.")
    parser.add_argument("--model", type=str, default="gpt-4.1", help="Model name.")
    parser.add_argument("--temperature", type=float, default=0.0,
                        help="Recommended to use 0.0 for deterministic judging.")

    parser.add_argument("--start", type=int, default=0, help="Start molecule index after id filtering.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Only process N molecules after start and id filtering.")
    parser.add_argument("--id_min", type=int, default=None,
                        help="Only process molecules with id >= id_min.")
    parser.add_argument("--id_max", type=int, default=None,
                        help="Only process molecules with id <= id_max.")

    parser.add_argument("--sleep", type=float, default=0.0,
                        help="Sleep seconds between triplet-level requests.")
    parser.add_argument("--save_every", type=int, default=1,
                        help="Save intermediate results every N judged triplets.")
    parser.add_argument("--use_json_mode", action="store_true",
                        help="Use response_format={'type':'json_object'} if the API provider supports it.")
    parser.add_argument("--skip_existing", action="store_true",
                        help="If output_file exists, skip triplets already judged by id and triplet_index.")
    parser.add_argument("--keep_failed_original", action="store_true",
                        help="If API fails, keep a deterministic no-delete fallback based on the original triplet.")
    parser.add_argument("--include_unsafe_in_corrected", action="store_true",
                        help="If set, final corrected_output_file will include final corrected triplets even when context_safe=false.")
    parser.add_argument("--semantic_retry", type=int, default=2,
                        help="Number of semantic retries when the model outputs delete/invalid corrected_triplet.")

    return parser.parse_args()


# ============================================================
# 3. Formula / ion / SMILES utilities
# ============================================================

ION_RE = re.compile(
    r"([A-Z][A-Za-z0-9?]*(?:\+|＋)?(?:[•·])?)\s*\(m/z\s*(\d+)\)"
)
FORMULA_RE = re.compile(r"([A-Z][a-z]?)(\d*)")


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(obj: Any, path: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def normalize_triplet(triplet: Any) -> Optional[List[str]]:
    if isinstance(triplet, list) and len(triplet) == 3:
        return [str(triplet[0]), str(triplet[1]), str(triplet[2])]
    return None


def parse_formula_counts(formula: str) -> Dict[str, int]:
    if not isinstance(formula, str):
        return {}

    formula = (
        formula.replace("+", "")
        .replace("＋", "")
        .replace("•", "")
        .replace("·", "")
        .replace("?", "")
    )

    counts: Dict[str, int] = defaultdict(int)
    for element, num in FORMULA_RE.findall(formula):
        counts[element] += int(num) if num else 1

    return dict(counts)


def nominal_mass(counts: Dict[str, int]) -> int:
    mass_table = {
        "H": 1,
        "C": 12,
        "N": 14,
        "O": 16,
        "F": 19,
        "P": 31,
        "S": 32,
        "Cl": 35,
        "Br": 79,
        "I": 127,
    }
    return sum(mass_table.get(element, 0) * n for element, n in counts.items())


def parse_ion(product_ion: str) -> Optional[Dict[str, Any]]:
    if not isinstance(product_ion, str):
        return None

    m = ION_RE.search(product_ion)
    if not m:
        return None

    formula = m.group(1)
    mz = int(m.group(2))
    counts = parse_formula_counts(formula)

    return {
        "formula": formula,
        "mz": mz,
        "counts": counts,
        "carbon": counts.get("C", 0),
        "hydrogen": counts.get("H", 0),
        "nominal_mass": nominal_mass(counts),
        "has_unknown": "?" in formula,
    }


def parse_precursor_mz(precursor: str) -> Optional[int]:
    if not isinstance(precursor, str):
        return None
    m = re.match(r"precursor_mz:\s*(\d+)", precursor.strip())
    return int(m.group(1)) if m else None


def count_c_in_smiles(smiles_fragment: str) -> int:
    if not isinstance(smiles_fragment, str):
        return 0
    return len(re.findall(r"C(?!l)", smiles_fragment))


def is_balanced_fragment(fragment: str) -> bool:
    balance = 0
    for ch in fragment:
        if ch == "(":
            balance += 1
        elif ch == ")":
            balance -= 1
            if balance < 0:
                return False
    return balance == 0


def parse_smiles_fragment_precursor(precursor: str) -> Tuple[Optional[str], List[str]]:
    if not isinstance(precursor, str) or not precursor.startswith("smiles_fragment:"):
        return None, []

    body = precursor.replace("smiles_fragment:", "", 1).strip()
    parts = body.split("|")
    best = parts[0].strip() if parts else None

    alternatives: List[str] = []
    if len(parts) > 1:
        m = re.search(r"alternatives:\s*\[(.*?)\]", parts[1])
        if m:
            alternatives = [
                x.strip().strip("'\"")
                for x in m.group(1).split(",")
                if x.strip()
            ]

    return best or None, alternatives


def format_smiles_fragment_candidate(candidates: List[str]) -> str:
    unique = list(dict.fromkeys([c for c in candidates if c]))
    if not unique:
        return "smiles_fragment: C"

    best = unique[0]
    alts = unique[1:4]
    if alts:
        return f"smiles_fragment: {best} | alternatives: [{', '.join(alts)}]"
    return f"smiles_fragment: {best}"


def enumerate_smiles_fragment_candidates(smiles: str, target_c: int, max_candidates: int = 8) -> List[str]:
    if not isinstance(smiles, str) or target_c <= 0:
        return []

    candidates: List[str] = []

    # Common exact linear fragment.
    linear = "C" * target_c
    if linear in smiles:
        candidates.append(linear)

    # Enumerate balanced substrings with exactly target_c carbon atoms.
    n = len(smiles)
    for i in range(n):
        for j in range(i + 1, n + 1):
            sub = smiles[i:j]
            if "C" not in sub:
                continue
            if count_c_in_smiles(sub) != target_c:
                continue
            if not sub.startswith("C"):
                continue
            if not (sub.endswith("C") or sub.endswith(")")):
                continue
            if not is_balanced_fragment(sub):
                continue
            if sub in smiles:
                candidates.append(sub)

    # Prefer branch-aware fragments when the source is branched, otherwise shorter exact fragments.
    def sort_key(x: str) -> Tuple[int, int, str]:
        has_branch = 1 if "(" in x or ")" in x else 0
        # branch first; then shorter; then lexical
        return (-has_branch, len(x), x)

    candidates = sorted(list(dict.fromkeys(candidates)), key=sort_key)
    return candidates[:max_candidates]


def get_structure_fragment_candidates(smiles: str, product_ion: str) -> List[str]:
    ion = parse_ion(product_ion)
    if ion is None:
        return []

    return enumerate_smiles_fragment_candidates(smiles, ion["carbon"])


def find_previous_ions_by_mz(previous_verified_triplets: List[List[str]], mz: int) -> List[Dict[str, Any]]:
    matched = []
    for triplet in previous_verified_triplets:
        if not isinstance(triplet, list) or len(triplet) != 3:
            continue
        ion = parse_ion(triplet[2])
        if ion is not None and ion["mz"] == mz:
            matched.append(ion)
    return matched


def get_same_carbon_higher_h_precursor_candidates(
    previous_verified_triplets: List[List[str]],
    product_ion: str,
) -> List[Dict[str, Any]]:
    product = parse_ion(product_ion)
    if product is None:
        return []

    candidates = []
    for triplet in previous_verified_triplets:
        ion = parse_ion(triplet[2]) if isinstance(triplet, list) and len(triplet) == 3 else None
        if ion is None:
            continue
        if ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]:
            candidates.append({
                "precursor_mz": ion["mz"],
                "precursor_ion": triplet[2],
                "source_triplet": triplet,
                "carbon": ion["carbon"],
                "hydrogen": ion["hydrogen"],
            })

    # Prefer nearest higher mass / hydrogen, but any same-carbon higher-H is acceptable.
    candidates.sort(key=lambda x: (x["precursor_mz"]))
    return candidates


def is_alkyl_like_ion(ion: Dict[str, Any]) -> bool:
    c = ion.get("carbon", 0)
    h = ion.get("hydrogen", 0)
    return c > 0 and h >= 2 * c + 1


def is_unsaturated_hydrocarbon_ion(ion: Dict[str, Any]) -> bool:
    c = ion.get("carbon", 0)
    h = ion.get("hydrogen", 0)
    return c > 0 and h < 2 * c + 1


def is_highly_unsaturated_hydrocarbon_ion(ion: Dict[str, Any]) -> bool:
    """
    Target ions such as C2H3+, C3H5+, C3H3+, C4H7+, C5H9+.
    These should generally not be explained by plain Sigma-bond cleavage when
    a dehydrogenation-style explanation is available.

    We intentionally use H <= 2C - 1 rather than H < 2C + 1 so that even-electron
    ions such as C4H8+ are not automatically rewritten away from Sigma-bond cleavage.
    """
    c = ion.get("carbon", 0)
    h = ion.get("hydrogen", 0)
    return c > 0 and h <= 2 * c - 1


def should_avoid_sigma_for_unsaturated_product(mechanism: str, product_ion: str) -> bool:
    if mechanism != "Sigma-bond cleavage":
        return False
    product = parse_ion(product_ion)
    if product is None:
        return False
    return is_highly_unsaturated_hydrocarbon_ion(product)


def choose_dehydrogenation_precursor(
    original_precursor: str,
    previous_verified_triplets: List[List[str]],
    product_ion: str,
) -> Optional[int]:
    """
    Choose a precursor_mz for same-carbon dehydrogenation.

    Priority:
    1. Keep the original precursor_mz if it is already supported by previous verified
       triplets and has the same carbon number with a higher hydrogen count.
    2. Otherwise choose the nearest same-carbon higher-H precursor, rather than
       blindly choosing the highest-H precursor. This avoids over-revising valid
       stepwise dehydrogenation paths.
    """
    product = parse_ion(product_ion)
    if product is None:
        return None

    original_mz = parse_precursor_mz(original_precursor)
    if original_mz is not None:
        previous_ions = find_previous_ions_by_mz(previous_verified_triplets, original_mz)
        for ion in previous_ions:
            if ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]:
                return original_mz

    candidates = get_same_carbon_higher_h_precursor_candidates(
        previous_verified_triplets,
        product_ion,
    )
    if not candidates:
        return None

    # Choose the closest higher-H precursor first; tie-break by smaller m/z.
    candidates.sort(key=lambda x: (x["hydrogen"] - product["hydrogen"], x["precursor_mz"]))
    return candidates[0]["precursor_mz"]


def is_reliable_for_precursor_context(triplet: List[str]) -> bool:
    """
    Decide whether a corrected triplet is strong enough to be reused as
    precursor_mz evidence in later ion-evolution decisions.

    This is intentionally stricter than context_safe:
    - Molecular ion can seed later context.
    - Sigma-bond cleavage with a structure-driven precursor can seed alkyl ions.
    - Dehydrogenation with precursor_mz can seed later dehydrogenation steps.
    - Dehydrogenation with only a smiles_fragment is kept in final output, but is
      not treated as strong precursor_mz evidence by default.
    """
    if not isinstance(triplet, list) or len(triplet) != 3:
        return False

    precursor, mechanism, product_ion = triplet

    if mechanism == "Molecular ion":
        return True

    if mechanism == "Sigma-bond cleavage":
        return isinstance(precursor, str) and precursor.startswith("smiles_fragment:")

    if mechanism == "Dehydrogenation / Sequential dehydrogenation":
        return parse_precursor_mz(precursor) is not None

    return False


def should_avoid_neutral_loss_for_hydrocarbon(
    mechanism: str,
    product_ion: str,
    molecule_formula: str,
) -> bool:
    """
    For pure hydrocarbons, avoid using Neutral loss to explain hydrocarbon cation
    formation. In cycloalkanes, carbon-conserving H-loss is better treated as
    dehydrogenation, while carbon-changing hydrocarbon loss is better treated as
    ring cleavage / ring rearrangement.
    """
    if mechanism != "Neutral loss":
        return False

    product = parse_ion(product_ion)
    mol_counts = parse_formula_counts(molecule_formula)
    if product is None or not mol_counts:
        return False

    molecule_is_hydrocarbon = set(mol_counts.keys()).issubset({"C", "H"})
    product_is_hydrocarbon = set(product["counts"].keys()).issubset({"C", "H"})
    return molecule_is_hydrocarbon and product_is_hydrocarbon


def is_hydrocarbon_counts(counts: Dict[str, int]) -> bool:
    return bool(counts) and set(counts.keys()).issubset({"C", "H"})


def format_hydrocarbon_formula(c_num: int, h_num: int) -> Optional[str]:
    if c_num <= 0 or h_num < 0:
        return None
    c_part = "C" if c_num == 1 else f"C{c_num}"
    h_part = "" if h_num == 0 else ("H" if h_num == 1 else f"H{h_num}")
    return f"{c_part}{h_part}+"


def is_product_ion_mass_consistent(product_ion: Any) -> bool:
    ion = parse_ion(product_ion)
    if ion is None:
        return False
    if ion.get("has_unknown"):
        return False
    return ion["nominal_mass"] == ion["mz"]


def repair_product_ion_formula_mz(product_ion: Any, molecule_formula: str = "") -> str:
    """
    Repair product-ion formula/mz mismatches while preserving the target m/z.

    Typical generator error in the uploaded cycloalkane results:
      C7H10+• (m/z 93)  ->  C7H9+ (m/z 93)
      C7H12+• (m/z 95)  ->  C7H11+ (m/z 95)

    The function only repairs pure hydrocarbon ions and keeps the same carbon
    number whenever that yields a valid nominal mass.
    """
    ion = parse_ion(product_ion)
    if ion is None:
        return str(product_ion)
    if ion["nominal_mass"] == ion["mz"] and not ion.get("has_unknown"):
        return str(product_ion)

    mol_counts = parse_formula_counts(molecule_formula)
    mol_c = mol_counts.get("C", 0)
    mz = int(ion["mz"])
    original_c = int(ion.get("carbon", 0))

    candidate_c: List[int] = []
    if original_c > 0:
        candidate_c.append(original_c)
    if mol_c > 0 and mol_c not in candidate_c:
        candidate_c.append(mol_c)
    # Last-resort hydrocarbon candidates, closest to original carbon first.
    max_c = mol_c if mol_c > 0 else max(original_c, mz // 12)
    for c_num in range(max_c, 0, -1):
        if c_num not in candidate_c:
            candidate_c.append(c_num)

    for c_num in candidate_c:
        if mol_c > 0 and c_num > mol_c:
            continue
        h_num = mz - 12 * c_num
        # EI hydrocarbon cations in this dataset should have non-negative H and
        # not exceed the saturated hydrocarbon envelope by a large margin.
        if h_num < 0:
            continue
        if h_num > 2 * c_num + 2:
            continue
        formula = format_hydrocarbon_formula(c_num, h_num)
        if formula:
            return f"{formula} (m/z {mz})"

    return str(product_ion)


def product_ion_change_allowed(original_product: Any, corrected_product: Any, molecule_formula: str = "") -> bool:
    """
    The prompt allows changing the product ion only when the original product
    formula/mz is internally inconsistent. This code-side validator implements
    that exception so the judge can fix formula errors instead of being forced to
    preserve an impossible product ion.
    """
    original = parse_ion(original_product)
    corrected = parse_ion(corrected_product)
    if original is None or corrected is None:
        return False
    if original["mz"] != corrected["mz"]:
        return False
    if is_product_ion_mass_consistent(original_product):
        return False
    if not is_product_ion_mass_consistent(corrected_product):
        return False
    mol_c = parse_formula_counts(molecule_formula).get("C", 0)
    if mol_c > 0 and corrected["carbon"] > mol_c:
        return False
    return True


def get_precursor_ion_by_mz(previous_verified_triplets: List[List[str]], precursor_mz: Optional[int]) -> Optional[Dict[str, Any]]:
    if precursor_mz is None:
        return None
    ions = find_previous_ions_by_mz(previous_verified_triplets, precursor_mz)
    return ions[0] if ions else None


def choose_neutral_loss_replacement_mechanism(
    precursor: str,
    product_ion: str,
    previous_verified_triplets: List[List[str]],
    molecule_formula: str,
) -> str:
    """
    Replace over-broad hydrocarbon Neutral loss with a cycloalkane-compatible
    mechanism.

    - Same-carbon H-loss: Dehydrogenation / Sequential dehydrogenation.
    - Carbon-changing hydrocarbon fragment formation: Ring cleavage / Ring rearrangement.
    """
    product = parse_ion(product_ion)
    if product is None:
        return "Ring cleavage / Ring rearrangement"

    precursor_mz = parse_precursor_mz(precursor)
    precursor_ion = get_precursor_ion_by_mz(previous_verified_triplets, precursor_mz)

    if precursor_ion is not None:
        if precursor_ion["carbon"] == product["carbon"] and precursor_ion["hydrogen"] > product["hydrogen"]:
            return "Dehydrogenation / Sequential dehydrogenation"
        return "Ring cleavage / Ring rearrangement"

    mol_counts = parse_formula_counts(molecule_formula)
    if is_hydrocarbon_counts(mol_counts):
        if mol_counts.get("C", 0) == product["carbon"] and mol_counts.get("H", 0) > product["hydrogen"]:
            return "Dehydrogenation / Sequential dehydrogenation"

    return "Ring cleavage / Ring rearrangement"


def is_primary_cycloalkane_ring_ion(product: Dict[str, Any]) -> bool:
    """
    CnH2n-1+ ions frequently arise from ring cleavage / rearrangement in
    cycloalkanes: C3H5+, C4H7+, C5H9+, C6H11+, C7H13+.
    """
    c_num = product.get("carbon", 0)
    h_num = product.get("hydrogen", 0)
    return 3 <= c_num <= 7 and h_num == 2 * c_num - 1


def is_common_cycloalkane_ring_fragment(product: Dict[str, Any]) -> bool:
    c_num = product.get("carbon", 0)
    h_num = product.get("hydrogen", 0)
    mz = product.get("mz", 0)
    common = {
        (2, 3, 27),
        (3, 3, 39), (3, 4, 40), (3, 5, 41),
        (4, 5, 53), (4, 6, 54), (4, 7, 55),
        (5, 5, 65), (5, 6, 66), (5, 7, 67), (5, 8, 68), (5, 9, 69),
        (6, 7, 79), (6, 9, 81), (6, 10, 82), (6, 11, 83),
        (7, 7, 91), (7, 9, 93), (7, 11, 95), (7, 13, 97),
    }
    return (c_num, h_num, mz) in common or is_primary_cycloalkane_ring_ion(product)


def restore_supported_original_dehydrogenation(
    original_triplet: List[str],
    final_triplet: List[str],
    previous_reliable_precursor_triplets: List[List[str]],
) -> List[str]:
    """
    Prevent over-revision to a higher-hydrogen precursor.

    If the original triplet is already a valid same-carbon dehydrogenation step
    supported by reliable previous context, keep the original triplet even if the
    model or postprocessor changed it to a more saturated precursor.
    """
    original = normalize_triplet(original_triplet)
    final = normalize_triplet(final_triplet)
    if original is None or final is None:
        return final_triplet

    orig_precursor, orig_mechanism, orig_product = original
    if orig_mechanism != "Dehydrogenation / Sequential dehydrogenation":
        return final_triplet

    orig_mz = parse_precursor_mz(orig_precursor)
    product = parse_ion(orig_product)
    if orig_mz is None or product is None:
        return final_triplet

    previous_ions = find_previous_ions_by_mz(previous_reliable_precursor_triplets, orig_mz)
    original_is_supported = any(
        ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]
        for ion in previous_ions
    )

    if original_is_supported:
        return original

    return final_triplet


def get_original_precursor_status(
    triplet: List[str],
    previous_reliable_precursor_triplets: List[List[str]],
) -> Dict[str, Any]:
    normalized = normalize_triplet(triplet)
    if normalized is None:
        return {"is_supported": False}

    precursor, mechanism, product_ion = normalized
    product = parse_ion(product_ion)
    precursor_mz = parse_precursor_mz(precursor)

    if product is None or precursor_mz is None:
        return {
            "is_supported": False,
            "original_precursor_mz": precursor_mz,
            "mechanism": mechanism,
            "product_ion": product_ion,
            "supporting_previous_ions": [],
        }

    previous_ions = find_previous_ions_by_mz(previous_reliable_precursor_triplets, precursor_mz)
    supporting_previous_ions = [
        ion for ion in previous_ions
        if ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]
    ]

    return {
        "is_supported": len(supporting_previous_ions) > 0,
        "original_precursor_mz": precursor_mz,
        "mechanism": mechanism,
        "product_ion": product_ion,
        "supporting_previous_ions": supporting_previous_ions,
    }


# ============================================================
# 4. Context safety and fallback generation
# ============================================================

def is_context_safe_triplet(
    triplet: List[str],
    previous_verified_triplets: List[List[str]],
    smiles: str,
    molecule_formula: str,
) -> Tuple[bool, List[str]]:
    reasons: List[str] = []

    if not isinstance(triplet, list) or len(triplet) != 3:
        return False, ["Triplet is not a valid 3-element list."]

    precursor, mechanism, product_ion = triplet
    product = parse_ion(product_ion)

    if product is None:
        return False, ["Cannot parse product ion formula/mz."]

    if not product.get("has_unknown") and product["nominal_mass"] != product["mz"]:
        reasons.append(
            f"Product ion formula/mz mismatch: formula={product['formula']}, "
            f"nominal_mass={product['nominal_mass']}, mz={product['mz']}."
        )

    mol_counts = parse_formula_counts(molecule_formula)
    mol_c = mol_counts.get("C", 0)
    if mol_c > 0 and product["carbon"] > mol_c:
        reasons.append(
            f"Product ion carbon number C{product['carbon']} exceeds molecule carbon number C{mol_c}."
        )

    if should_avoid_sigma_for_unsaturated_product(mechanism, product_ion):
        reasons.append(
            "Plain Sigma-bond cleavage is not safe as context for a highly unsaturated "
            "hydrocarbon ion; prefer same-carbon dehydrogenation when available."
        )

    precursor_mz = parse_precursor_mz(precursor)

    if isinstance(precursor, str) and precursor.startswith("smiles_fragment:"):
        best_fragment, alternatives = parse_smiles_fragment_precursor(precursor)
        all_fragments = [best_fragment] + alternatives
        valid_fragments = [frag for frag in all_fragments if frag and frag in smiles]

        if not valid_fragments:
            reasons.append(f"No smiles_fragment candidate is a substring of source SMILES '{smiles}'.")
        else:
            if best_fragment not in valid_fragments:
                reasons.append(
                    f"Best smiles_fragment '{best_fragment}' is invalid, although valid alternatives exist: {valid_fragments}."
                )

            if best_fragment:
                frag_c = count_c_in_smiles(best_fragment)
                prod_c = product["carbon"]

                if prod_c > 0 and frag_c < prod_c:
                    reasons.append(
                        f"Best smiles_fragment carbon number C{frag_c} is smaller than product ion carbon number C{prod_c}."
                    )

                # For sigma-bond cleavage, an exact-carbon fragment is safer for context memory.
                if mechanism == "Sigma-bond cleavage" and prod_c > 0 and frag_c != prod_c:
                    reasons.append(
                        f"For Sigma-bond cleavage, best smiles_fragment carbon number C{frag_c} should match product ion carbon number C{prod_c} for safe context use."
                    )

    if precursor_mz is not None:
        previous_ions = find_previous_ions_by_mz(previous_verified_triplets, precursor_mz)

        if not previous_ions:
            reasons.append(f"precursor_mz:{precursor_mz} is not supported by previous verified corrected triplets.")

        if mechanism == "Dehydrogenation / Sequential dehydrogenation" and previous_ions:
            same_carbon_higher_h_exists = any(
                prev_ion["carbon"] == product["carbon"]
                and prev_ion["hydrogen"] > product["hydrogen"]
                for prev_ion in previous_ions
            )
            if not same_carbon_higher_h_exists:
                reasons.append(
                    "Invalid dehydrogenation: precursor and product do not preserve carbon number "
                    "or precursor does not have a higher hydrogen count."
                )

        if mechanism == "Sigma-bond cleavage":
            reasons.append(
                "Sigma-bond cleavage with precursor_mz is not safe as sequential context; "
                "prefer structure-driven smiles_fragment for Sigma-bond cleavage."
            )

    return len(reasons) == 0, reasons


def sanitize_triplet(
    triplet: List[str],
    record: Dict[str, Any],
    previous_verified_triplets: List[List[str]],
) -> List[str]:
    """
    Deterministic cleanup after the LLM judge.

    This version is intentionally conservative: it fixes hard chemical/formula
    errors found in the uploaded cycloalkane results, but it does not rewrite a
    reasonable ring-cleavage explanation merely for stylistic preference.
    """
    precursor, mechanism, product_ion = triplet
    smiles = record.get("smiles", "")
    molecule_formula = record.get("formula", "")

    # 1) Repair formula/mz mismatch while preserving m/z.
    repaired_product_ion = repair_product_ion_formula_mz(product_ion, molecule_formula)
    if repaired_product_ion != product_ion:
        product_ion = repaired_product_ion

    product = parse_ion(product_ion)
    if product is None:
        return [precursor, mechanism, product_ion]

    # 2) Isotopic peak is not valid for M-1 style hydrocarbon ions such as
    # C7H10+• (m/z 93). After formula repair, treat same-carbon H-loss as
    # dehydrogenation if possible; otherwise fall back to ring cleavage.
    if mechanism == "Isotopic peak":
        mol_counts = parse_formula_counts(molecule_formula)
        if is_hydrocarbon_counts(mol_counts) and product["mz"] <= nominal_mass(mol_counts):
            chosen_mz = choose_dehydrogenation_precursor(
                original_precursor=precursor,
                previous_verified_triplets=previous_verified_triplets,
                product_ion=product_ion,
            )
            if chosen_mz is not None:
                return [
                    f"precursor_mz: {chosen_mz}",
                    "Dehydrogenation / Sequential dehydrogenation",
                    product_ion,
                ]
            if mol_counts.get("C", 0) == product["carbon"] and mol_counts.get("H", 0) > product["hydrogen"]:
                return [
                    f"smiles_fragment: {smiles}",
                    "Dehydrogenation / Sequential dehydrogenation",
                    product_ion,
                ]
            return [precursor, "Ring cleavage / Ring rearrangement", product_ion]

    # 3) In pure hydrocarbon cycloalkanes, broad "Neutral loss" should not be
    # used for generic hydrocarbon cation formation.
    if should_avoid_neutral_loss_for_hydrocarbon(
        mechanism=mechanism,
        product_ion=product_ion,
        molecule_formula=molecule_formula,
    ):
        replacement = choose_neutral_loss_replacement_mechanism(
            precursor=precursor,
            product_ion=product_ion,
            previous_verified_triplets=previous_verified_triplets,
            molecule_formula=molecule_formula,
        )
        return [precursor, replacement, product_ion]

    # 4) For primary/common cycloalkane ring ions, keep/recover ring cleavage
    # rather than forcing dehydrogenation or sigma cleavage.
    if is_common_cycloalkane_ring_fragment(product):
        if mechanism in {"Sigma-bond cleavage", "Neutral loss"}:
            return [precursor, "Ring cleavage / Ring rearrangement", product_ion]

    # 5) Avoid plain Sigma-bond cleavage for highly unsaturated hydrocarbon ions
    # only when the product is not a primary/common cycloalkane ring fragment.
    if should_avoid_sigma_for_unsaturated_product(mechanism, product_ion) and not is_common_cycloalkane_ring_fragment(product):
        chosen_mz = choose_dehydrogenation_precursor(
            original_precursor=precursor,
            previous_verified_triplets=previous_verified_triplets,
            product_ion=product_ion,
        )
        if chosen_mz is not None:
            return [
                f"precursor_mz: {chosen_mz}",
                "Dehydrogenation / Sequential dehydrogenation",
                product_ion,
            ]

        if isinstance(precursor, str) and precursor.startswith("smiles_fragment:"):
            return [precursor, "Ring cleavage / Ring rearrangement", product_ion]

        candidates = get_structure_fragment_candidates(smiles, product_ion)
        if candidates:
            return [format_smiles_fragment_candidate(candidates), "Ring cleavage / Ring rearrangement", product_ion]

    # 6) Fix structure-driven sigma precursor if a better exact-carbon candidate exists.
    # Do not apply this to Ring cleavage, because for cycloalkanes a full-ring or
    # parent-skeleton smiles_fragment can be a source marker rather than an exact
    # neutral precursor.
    if mechanism == "Sigma-bond cleavage" and isinstance(precursor, str) and precursor.startswith("smiles_fragment:"):
        candidates = get_structure_fragment_candidates(smiles, product_ion)
        best_fragment, _ = parse_smiles_fragment_precursor(precursor)
        best_c = count_c_in_smiles(best_fragment) if best_fragment else 0

        if candidates and (
            best_fragment not in smiles
            or best_c < product["carbon"]
            or best_c != product["carbon"]
        ):
            return [format_smiles_fragment_candidate(candidates), mechanism, product_ion]

    # 7) Fix unsupported dehydrogenation precursor_mz.
    if mechanism == "Dehydrogenation / Sequential dehydrogenation":
        precursor_mz = parse_precursor_mz(precursor)
        prev_ions = find_previous_ions_by_mz(previous_verified_triplets, precursor_mz) if precursor_mz else []

        supported = any(
            ion["carbon"] == product["carbon"] and ion["hydrogen"] > product["hydrogen"]
            for ion in prev_ions
        )
        if not supported:
            chosen_mz = choose_dehydrogenation_precursor(
                original_precursor=precursor,
                previous_verified_triplets=previous_verified_triplets,
                product_ion=product_ion,
            )
            if chosen_mz is not None:
                return [
                    f"precursor_mz: {chosen_mz}",
                    "Dehydrogenation / Sequential dehydrogenation",
                    product_ion,
                ]
            # If not supported, carbon-changing or unsupported same-carbon paths
            # should not be kept as dehydrogenation in cycloalkanes.
            return [precursor, "Ring cleavage / Ring rearrangement", product_ion]

    return [precursor, mechanism, product_ion]


def fallback_corrected_triplet(
    record: Dict[str, Any],
    original_triplet: List[str],
    previous_verified_triplets: List[List[str]],
) -> List[str]:
    """
    Deterministic no-delete fallback. It always returns a non-empty 3-element triplet.

    Compared with the previous version, this fallback first repairs impossible
    product formula/mz pairs and then chooses a cycloalkane-aware mechanism.
    """
    smiles = record.get("smiles", "")
    formula = record.get("formula", "")
    product_ion = repair_product_ion_formula_mz(original_triplet[2], formula)
    product = parse_ion(product_ion)

    if product is None:
        return [f"smiles_fragment: {smiles}", "Ring cleavage / Ring rearrangement", product_ion]

    mol_counts = parse_formula_counts(formula)
    if mol_counts and product["counts"] == mol_counts:
        return [f"smiles_fragment: {smiles}", "Molecular ion", product_ion]

    # Same-carbon higher-H precursor from verified context.
    chosen_mz = choose_dehydrogenation_precursor(
        original_precursor=original_triplet[0],
        previous_verified_triplets=previous_verified_triplets,
        product_ion=product_ion,
    )
    if chosen_mz is not None and not is_primary_cycloalkane_ring_ion(product):
        return [
            f"precursor_mz: {chosen_mz}",
            "Dehydrogenation / Sequential dehydrogenation",
            product_ion,
        ]

    # Structure-driven candidate with exact carbon count.
    frag_cands = get_structure_fragment_candidates(smiles, product_ion)
    precursor = format_smiles_fragment_candidate(frag_cands) if frag_cands else f"smiles_fragment: {smiles}"

    if is_alkyl_like_ion(product):
        mechanism = "Sigma-bond cleavage"
    else:
        mechanism = "Ring cleavage / Ring rearrangement"

    return [precursor, mechanism, product_ion]


def _clean_llm_text_field(value: Any) -> str:
    """Return a non-empty model-provided text field when available."""
    if value is None:
        return ""
    text = str(value).strip()
    return text


def make_fallback_judge_output(
    record: Dict[str, Any],
    original_triplet: List[str],
    previous_verified_triplets: List[List[str]],
    reason_prefix: str,
    model_reason: Optional[str] = None,
    model_overall_quality: Optional[str] = None,
    model_major_errors: Optional[List[Any]] = None,
    model_recommended_strategy: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Build a schema-valid no-delete fallback while preserving the model-written
    reason whenever the model returned one.

    Important:
    - The judge prompt is not changed.
    - If the model output contains a usable reason, that reason is kept as the
      final judge_output['reason'].
    - Deterministic fallback text is used only when no model-written reason exists,
      which can happen after API/JSON parsing failure or a severely malformed reply.
    """
    corrected = fallback_corrected_triplet(record, original_triplet, previous_verified_triplets)
    corrected = sanitize_triplet(corrected, record, previous_verified_triplets)

    llm_reason = _clean_llm_text_field(model_reason)
    if not llm_reason:
        llm_reason = (
            f"{reason_prefix} For this cycloalkane EI-MS triplet, "
            "a no-delete fallback was applied to preserve the target product ion "
            "and produce a chemically plausible precursor/mechanism."
        )

    llm_overall_quality = _clean_llm_text_field(model_overall_quality)
    if not llm_overall_quality:
        llm_overall_quality = (
            "Automatically revised by the cycloalkane no-delete fallback after "
            "the model response could not be used as a valid strict JSON judge output."
        )

    if isinstance(model_major_errors, list) and model_major_errors:
        major_errors = model_major_errors
    else:
        major_errors = [
            "Cycloalkane judge output was invalid, empty, or used a forbidden delete/empty corrected_triplet."
        ]

    llm_recommended_strategy = _clean_llm_text_field(model_recommended_strategy)
    if not llm_recommended_strategy:
        llm_recommended_strategy = (
            "Use the fallback corrected_triplet for the cycloalkane / alicyclic EI-MS record, "
            "and inspect chemical_warnings/context_safe before reusing it as later precursor context."
        )

    return {
        "id": record.get("id", None),
        "name": record.get("name", ""),
        "smiles": record.get("smiles", ""),
        "formula": record.get("formula", ""),
        "mw": record.get("mw", ""),
        "original_triplet": original_triplet,
        "verdict": "revise",
        "reason": llm_reason,
        "corrected_triplet": corrected,
        "overall_quality": llm_overall_quality,
        "major_errors": major_errors,
        "recommended_strategy": llm_recommended_strategy,
    }


# ============================================================
# 5. API / JSON utilities
# ============================================================

def extract_json_from_text(text: str) -> Dict[str, Any]:
    if text is None:
        raise ValueError("Empty response content.")

    raw = text.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.IGNORECASE)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass

    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        candidate = raw[start:end + 1]
        return json.loads(candidate)

    raise ValueError(f"Cannot parse JSON from response:\n{raw[:1000]}")


def validate_judge_output(parsed: Dict[str, Any]) -> List[str]:
    warnings: List[str] = []
    required_keys = [
        "id", "name", "smiles", "formula", "mw",
        "original_triplet", "verdict", "reason", "corrected_triplet",
        "overall_quality", "major_errors", "recommended_strategy",
    ]

    for key in required_keys:
        if key not in parsed:
            warnings.append(f"Missing key: {key}")

    verdict = parsed.get("verdict")
    if verdict not in ["accept", "revise"]:
        warnings.append(f"Invalid or forbidden verdict: {verdict}")

    if normalize_triplet(parsed.get("original_triplet")) is None:
        warnings.append("Cycloalkane judge original_triplet is not a valid 3-element EI-MS triplet list.")

    if normalize_triplet(parsed.get("corrected_triplet")) is None:
        warnings.append("Cycloalkane judge corrected_triplet must be a non-empty valid 3-element EI-MS triplet list.")

    if not isinstance(parsed.get("major_errors"), list):
        warnings.append("Cycloalkane judge major_errors is not a list.")

    original = normalize_triplet(parsed.get("original_triplet"))
    corrected = normalize_triplet(parsed.get("corrected_triplet"))
    if original is not None and corrected is not None and original[2] != corrected[2]:
        if not product_ion_change_allowed(original[2], corrected[2], parsed.get("formula", "")):
            warnings.append(
                "Cycloalkane judge corrected_triplet changed the target product ion without the allowed formula/mz-mismatch exception."
            )

    return warnings


def normalize_revise_without_change(parsed: Dict[str, Any]) -> Dict[str, Any]:
    """
    If the model says verdict=revise but corrected_triplet is identical to
    original_triplet, normalize the verdict to accept.

    The model-written reason is deliberately preserved. Earlier versions appended
    a code-generated explanation to the reason field, but in this version the
    reason field should come from the large model whenever a valid model response
    exists.
    """
    if not isinstance(parsed, dict):
        return parsed

    original = normalize_triplet(parsed.get("original_triplet"))
    corrected = normalize_triplet(parsed.get("corrected_triplet"))

    if parsed.get("verdict") == "revise" and original is not None and corrected == original:
        parsed["verdict"] = "accept"
        major_errors = parsed.get("major_errors", [])
        if isinstance(major_errors, list) and not major_errors:
            parsed["overall_quality"] = parsed.get(
                "overall_quality",
                "Chemically reasonable for a cycloalkane EI-MS triplet; normalized to accept because no actual triplet change was made.",
            )

    return parsed


def enforce_current_record_metadata(
    parsed: Dict[str, Any],
    record: Dict[str, Any],
    original_triplet: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """
    Force saved metadata to match the current input molecule.

    This prevents the model from accidentally returning a renumbered id such as 1, 2, 3...
    when the current molecule actually has an original dataset id such as 75, 76, ...
    """
    if not isinstance(parsed, dict):
        return parsed

    parsed["id"] = record.get("id", None)
    parsed["name"] = record.get("name", "")
    parsed["smiles"] = record.get("smiles", "")
    parsed["formula"] = record.get("formula", "")
    parsed["mw"] = record.get("mw", "")

    if original_triplet is not None:
        parsed["original_triplet"] = original_triplet

    return parsed


def has_hard_format_error(warnings: List[str]) -> bool:
    hard_patterns = [
        "Missing key",
        "Invalid or forbidden verdict",
        "corrected_triplet must be a non-empty",
        "original_triplet is not a valid",
        "changed the target product ion without the allowed formula/mz-mismatch exception",
    ]
    return any(any(pattern in warning for pattern in hard_patterns) for warning in warnings)


def build_user_prompt(
    record: Dict[str, Any],
    triplet: List[str],
    triplet_index: int,
    previous_verified_corrected_triplets: List[List[str]],
    previous_reliable_precursor_triplets: List[List[str]],
) -> str:
    product_ion = triplet[2]
    payload = {
        "id": record.get("id", None),
        "name": record.get("name", ""),
        "smiles": record.get("smiles", ""),
        "formula": record.get("formula", ""),
        "mw": record.get("mw", ""),
        "triplet_index": triplet_index,
        "original_triplet": triplet,

        "all_original_triplets_for_this_molecule": record.get("_judge_triplets_flat", record.get("triplets", [])),
        "previous_verified_corrected_triplets_for_this_molecule": previous_verified_corrected_triplets,
        "previous_reliable_precursor_triplets_for_this_molecule": previous_reliable_precursor_triplets,
        "original_precursor_status": get_original_precursor_status(
            triplet,
            previous_reliable_precursor_triplets,
        ),

        # New model-facing hints.
        "same_carbon_higher_h_precursor_candidates": get_same_carbon_higher_h_precursor_candidates(
            previous_reliable_precursor_triplets,
            product_ion,
        ),
        "structure_fragment_candidates_for_product": get_structure_fragment_candidates(
            record.get("smiles", ""),
            product_ion,
        ),
    }

    if "compound_class" in record:
        payload["compound_class"] = record.get("compound_class")
    if "spectrum" in record:
        payload["spectrum"] = record.get("spectrum")
    if "input_spectrum" in record:
        payload["input_spectrum"] = record.get("input_spectrum")

    return (
        "Please judge the following existing EI-MS fragmentation triplet for a cycloalkane molecule.\n"
        "You must output only verdict='accept' or verdict='revise'. The verdict 'delete' is forbidden.\n"
        "You must always provide a non-empty corrected_triplet and keep the existing JSON output schema unchanged.\n"
        "If the original precursor/mechanism is wrong, revise it so that the same target product ion is generated.\n"
        "Before deciding the verdict, perform the mandatory smiles_fragment audit from the system prompt.\n"
        "For every non-molecular-ion smiles_fragment, compare: "
        "(a) parent carbon count, (b) fragment carbon count, and (c) product-ion carbon count.\n"
        "If the fragment is the complete source SMILES but the product ion has fewer carbons than the parent, "
        "you MUST revise the fragment; accepting the full parent as a generic source marker is forbidden.\n"
        "If fragment carbon count differs from product-ion carbon count, revise the precursor to an exact-carbon, "
        "connected, source-verifiable structural fragment whenever possible.\n"
        "Use structure_fragment_candidates_for_product as grounded options for all structure-driven mechanisms, "
        "including Ring cleavage / Ring rearrangement and Sigma-bond cleavage, but select by connectivity, branching, "
        "and mechanism compatibility rather than blindly choosing the first candidate.\n"
        "If the mechanism and product ion are already reasonable and only the fragment is wrong, change only "
        "corrected_triplet[0]; preserve corrected_triplet[1] and corrected_triplet[2].\n"
        "Never repair an oversized fragment by inventing a generic C, CC, or CCC placeholder. The corrected fragment "
        "must be an actual connected structural region of this specific source SMILES and must correspond to the product ion.\n"
        "Use same_carbon_higher_h_precursor_candidates for sequential dehydrogenation when possible, "
        "but do not replace an already valid original precursor_mz merely because a higher-H precursor also exists.\n"
        "For Dehydrogenation / Sequential dehydrogenation, precursor and product must preserve carbon number.\n"
        "For highly unsaturated hydrocarbon ions such as C2H3+, C3H5+, C3H3+, C4H7+, and C5H9+, "
        "avoid plain Sigma-bond cleavage when a chemically supported dehydrogenation or ring-derived path is more consistent.\n"
        "For Sigma-bond cleavage, prefer a structure-driven smiles_fragment over precursor_mz.\n"
        "Do not assume any future triplet has already been corrected.\n"
        "Perform all audits internally and return strict JSON only according to the unchanged system schema.\n\n"
        "[Triplet judgment input]\n"
        f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
    )


def call_api_once(
    client: OpenAI,
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
    max_tokens: int,
    use_json_mode: bool = False,
) -> str:
    kwargs = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if use_json_mode:
        kwargs["response_format"] = {"type": "json_object"}

    completion = client.chat.completions.create(**kwargs)
    return completion.choices[0].message.content


def call_api_with_token_retry(
    client: OpenAI,
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
    use_json_mode: bool,
) -> Tuple[Optional[Dict[str, Any]], str, Optional[str]]:
    token_attempts = [30000, 60000, 16384]
    raw_text = ""
    last_error = None

    for attempt, current_max_tokens in enumerate(token_attempts, start=1):
        try:
            print(f"[Token Attempt {attempt}/{len(token_attempts)}] max_tokens={current_max_tokens}")
            raw_text = call_api_once(
                client=client,
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=current_max_tokens,
                use_json_mode=use_json_mode,
            )
            parsed = extract_json_from_text(raw_text)
            return parsed, raw_text, None

        except Exception as e:
            last_error = str(e)
            print(
                f"[Token Attempt {attempt}/{len(token_attempts)}] "
                f"API or JSON parsing failed with max_tokens={current_max_tokens}: {last_error}"
            )

            if use_json_mode and ("response_format" in last_error or "json" in last_error.lower()):
                try:
                    print(f"[Fallback without json mode] max_tokens={current_max_tokens}")
                    raw_text = call_api_once(
                        client=client,
                        model=model,
                        messages=messages,
                        temperature=temperature,
                        max_tokens=current_max_tokens,
                        use_json_mode=False,
                    )
                    parsed = extract_json_from_text(raw_text)
                    return parsed, raw_text, None
                except Exception as e2:
                    last_error = str(e2)
                    print(f"[Fallback without json mode failed] {last_error}")

            if attempt < len(token_attempts):
                time.sleep(3)

    return None, raw_text, last_error


def semantic_retry_if_needed(
    client: OpenAI,
    model: str,
    messages: List[Dict[str, str]],
    parsed: Optional[Dict[str, Any]],
    raw_text: str,
    temperature: float,
    use_json_mode: bool,
    max_retries: int,
) -> Tuple[Optional[Dict[str, Any]], str, List[str], bool]:
    """
    Retry when the model violates the no-delete / non-empty corrected_triplet schema.
    """
    if parsed is None:
        return parsed, raw_text, ["Initial parsed output is None."], False

    warnings = validate_judge_output(parsed)
    if not has_hard_format_error(warnings):
        return parsed, raw_text, warnings, False

    current_parsed = parsed
    current_raw = raw_text
    current_warnings = warnings

    for retry_idx in range(1, max_retries + 1):
        print(f"[Semantic Retry {retry_idx}/{max_retries}] hard warnings: {current_warnings}")

        retry_messages = messages + [
            {"role": "assistant", "content": current_raw},
            {
                "role": "user",
                "content": (
                    "Your previous JSON violates the required no-delete schema. "
                    "You must output strict JSON only. "
                    "verdict must be only 'accept' or 'revise'. "
                    "The verdict 'delete' is forbidden. "
                    "corrected_triplet must be a non-empty 3-element list. "
                    "Preserve the same target product ion as the original_triplet. "
                    "If the original precursor or mechanism is wrong, revise it using a valid "
                    "previous precursor candidate or a structure-driven smiles_fragment."
                ),
            },
        ]

        retry_parsed, retry_raw, retry_error = call_api_with_token_retry(
            client=client,
            model=model,
            messages=retry_messages,
            temperature=temperature,
            use_json_mode=use_json_mode,
        )

        if retry_parsed is None:
            current_warnings = [f"Semantic retry failed: {retry_error}"]
            continue

        retry_warnings = validate_judge_output(retry_parsed)
        current_parsed = retry_parsed
        current_raw = retry_raw
        current_warnings = retry_warnings

        if not has_hard_format_error(retry_warnings):
            return current_parsed, current_raw, current_warnings, True

    return current_parsed, current_raw, current_warnings, True


# ============================================================
# 6. Corrected output extraction
# ============================================================

def build_corrected_outputs(
    input_records: List[Dict[str, Any]],
    full_results: List[Dict[str, Any]],
    include_unsafe_in_corrected: bool = False,
) -> List[Dict[str, Any]]:
    grouped: Dict[Any, Dict[str, Any]] = {}

    for record in input_records:
        data_id = record.get("id", None)
        grouped[data_id] = {
            "id": data_id,
            "name": record.get("name", ""),
            "smiles": record.get("smiles", ""),
            "formula": record.get("formula", ""),
            "mw": record.get("mw", ""),
            "corrected_triplet": [],
        }

    for item in full_results:
        data_id = item.get("id", None)
        if data_id not in grouped:
            grouped[data_id] = {
                "id": data_id,
                "name": item.get("name", ""),
                "smiles": item.get("smiles", ""),
                "formula": item.get("formula", ""),
                "mw": item.get("mw", ""),
                "corrected_triplet": [],
            }

        final_triplet = normalize_triplet(item.get("final_corrected_triplet"))

        # No-delete output policy:
        # context_safe only controls whether a triplet can be reused as later context.
        # It must not filter the final corrected_output_file, otherwise unsafe triplets
        # would be silently removed and behave like delete.
        if final_triplet is not None:
            grouped[data_id]["corrected_triplet"].append(final_triplet)

    return list(grouped.values())


# ============================================================
# 6.1 Input triplet extraction
# ============================================================

def get_judge_triplets_from_record(record: Dict[str, Any]) -> List[List[str]]:
    """
    Extract judge input triplets without changing the external input format.

    Supported formats:
    1. Existing judge input: record["triplets"] = [[src, mech, product], ...]
    2. Generator result format in the uploaded result file:
       record["model_output"]["triples"][mz]["triplet"] = [[src, mech, product], ...]
    3. Corrected-style input: record["corrected_triplet"] = [...]

    The output format of this script is unchanged; this function only makes the
    reader robust to the nested cycloalkane generation result format.
    """
    raw = record.get("triplets")
    if isinstance(raw, list) and raw:
        out = []
        for item in raw:
            t = normalize_triplet(item)
            if t is not None:
                out.append(t)
        if out:
            return out

    raw = record.get("corrected_triplet")
    if isinstance(raw, list) and raw:
        out = []
        for item in raw:
            t = normalize_triplet(item)
            if t is not None:
                out.append(t)
        if out:
            return out

    triples_obj = None
    if isinstance(record.get("model_output"), dict):
        triples_obj = record["model_output"].get("triples")
    if triples_obj is None and isinstance(record.get("triples"), dict):
        triples_obj = record.get("triples")

    out: List[List[str]] = []
    if isinstance(triples_obj, dict):
        def _mz_sort_key(x: Any) -> Tuple[float, str]:
            try:
                return (float(x), str(x))
            except Exception:
                return (float("inf"), str(x))

        for mz_key in sorted(triples_obj.keys(), key=_mz_sort_key, reverse=True):
            block = triples_obj.get(mz_key)
            if not isinstance(block, dict):
                continue
            raw_triplet = block.get("triplet", [])
            if normalize_triplet(raw_triplet) is not None:
                out.append(normalize_triplet(raw_triplet))
                continue
            if isinstance(raw_triplet, list):
                for item in raw_triplet:
                    t = normalize_triplet(item)
                    if t is not None:
                        out.append(t)

    # Preserve order but remove exact duplicates.
    deduped: List[List[str]] = []
    seen = set()
    for t in out:
        key = json.dumps(t, ensure_ascii=False)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(t)
    return deduped


# ============================================================
# 7. Main process
# ============================================================

def filter_records(records: List[Dict[str, Any]], args: argparse.Namespace) -> List[Dict[str, Any]]:
    selected = []
    for record in records:
        rid_raw = record.get("id", None)
        try:
            rid = int(rid_raw)
        except Exception:
            rid = None

        if args.id_min is not None and rid is not None and rid < args.id_min:
            continue
        if args.id_max is not None and rid is not None and rid > args.id_max:
            continue
        selected.append(record)

    if args.limit is None:
        return selected[args.start:]
    return selected[args.start:args.start + args.limit]


def main() -> None:
    args = parse_args()

    api_key = args.api_key or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("API key is missing. Please pass --api_key or set OPENAI_API_KEY.")

    client = OpenAI(api_key=api_key)

    records = load_json(args.input_file)
    if isinstance(records, dict):
        records = [records]
    if not isinstance(records, list):
        raise ValueError("Input JSON must be a list or a single dict.")

    selected_records = filter_records(records, args)

    full_results: List[Dict[str, Any]] = []
    processed_keys = set()
    existing_by_key: Dict[Tuple[Any, Any], Dict[str, Any]] = {}

    if args.skip_existing and os.path.exists(args.output_file):
        try:
            full_results = load_json(args.output_file)
            for item in full_results:
                key = (item.get("id"), item.get("triplet_index"))
                processed_keys.add(key)
                existing_by_key[key] = item
            print(f"Loaded {len(full_results)} existing judge results.")
        except Exception as e:
            print(f"Failed to load existing output file. Start from empty results. Error: {e}")
            full_results = []
            processed_keys = set()
            existing_by_key = {}

    total_triplets = sum(len(get_judge_triplets_from_record(r)) for r in selected_records if isinstance(r, dict))

    print("=" * 80)
    print(f"Total selected cycloalkane / alicyclic hydrocarbon molecules: {len(selected_records)}")
    print(f"Total triplets to judge: {total_triplets}")
    print(f"id_min={args.id_min}, id_max={args.id_max}, start={args.start}, limit={args.limit}")
    print(f"Model: {args.model}")
    print(f"Full output file: {args.output_file}")
    print(f"Corrected output file: {args.corrected_output_file}")
    print(f"include_unsafe_in_corrected: {args.include_unsafe_in_corrected}")
    print("=" * 80)

    judged_count = 0

    for record_idx, record in enumerate(selected_records, start=1):
        if not isinstance(record, dict):
            continue

        data_id = record.get("id", None)
        name = record.get("name", "")
        smiles = record.get("smiles", "")
        formula = record.get("formula", "")
        mw = record.get("mw", "")
        triplets = get_judge_triplets_from_record(record)
        record["_judge_triplets_flat"] = triplets

        previous_verified_corrected_triplets: List[List[str]] = []
        previous_reliable_precursor_triplets: List[List[str]] = []

        if not isinstance(triplets, list):
            print(f"[Skip] id={data_id}: triplets is not a list.")
            continue

        print("=" * 80)
        print(
            f"[Molecule {record_idx}/{len(selected_records)}] "
            f"id={data_id}, name={name}, smiles={smiles}, formula={formula}, mw={mw}, "
            f"triplets={len(triplets)}"
        )

        for triplet_index, triplet in enumerate(triplets):
            normalized_triplet = normalize_triplet(triplet)

            previous_before_current = previous_verified_corrected_triplets[:]
            previous_reliable_before_current = previous_reliable_precursor_triplets[:]

            if normalized_triplet is None:
                fallback = fallback_corrected_triplet(
                    record=record,
                    original_triplet=["", "Sigma-bond cleavage", ""],
                    previous_verified_triplets=previous_verified_corrected_triplets,
                )
                result_item = {
                    "id": data_id,
                    "name": name,
                    "smiles": smiles,
                    "formula": formula,
                    "mw": mw,
                    "triplet_index": triplet_index,
                    "original_triplet": triplet,
                    "judge_output": None,
                    "model_judge_output_before_fallback": None,
                    "final_corrected_triplet": fallback,
                    "auto_fallback_used": True,
                    "raw_response": "",
                    "parse_ok": False,
                    "error": "Invalid cycloalkane judge input triplet format; expected a 3-element EI-MS triplet list.",
                    "warnings": ["Invalid cycloalkane judge input triplet format."],
                    "chemical_warnings": ["Invalid cycloalkane judge input triplet format."],
                    "context_safe": False,
                    "context_reliable_for_precursor": False,
                    "triplet_postprocess_modified": False,
                    "verdict_postprocess_modified": False,
                    "previous_verified_corrected_triplets_before_current": previous_before_current,
                    "previous_reliable_precursor_triplets_before_current": previous_reliable_before_current,
                }
                full_results.append(result_item)
                continue

            key = (data_id, triplet_index)
            if args.skip_existing and key in processed_keys:
                print(f"[Skip existing] id={data_id}, triplet_index={triplet_index}")
                existing_item = existing_by_key.get(key)
                if existing_item:
                    final_triplet = normalize_triplet(existing_item.get("final_corrected_triplet"))
                    if final_triplet is not None and existing_item.get("context_safe", False):
                        previous_verified_corrected_triplets.append(final_triplet)
                        if existing_item.get("context_reliable_for_precursor", False) or is_reliable_for_precursor_context(final_triplet):
                            previous_reliable_precursor_triplets.append(final_triplet)
                continue

            judged_count += 1
            print("-" * 80)
            print(
                f"[Judge {judged_count}/{total_triplets}] "
                f"id={data_id}, triplet_index={triplet_index}, triplet={normalized_triplet}"
            )
            print(f"Previous verified corrected triplets available: {len(previous_verified_corrected_triplets)}")

            user_prompt = build_user_prompt(
                record=record,
                triplet=normalized_triplet,
                triplet_index=triplet_index,
                previous_verified_corrected_triplets=previous_before_current,
                previous_reliable_precursor_triplets=previous_reliable_before_current,
            )
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ]

            parsed, raw_text, error = call_api_with_token_retry(
                client=client,
                model=args.model,
                messages=messages,
                temperature=args.temperature,
                use_json_mode=args.use_json_mode,
            )

            model_judge_output_before_fallback = None
            parse_ok = parsed is not None
            semantic_retry_used = False

            if parsed is not None:
                parsed, raw_text, warnings, semantic_retry_used = semantic_retry_if_needed(
                    client=client,
                    model=args.model,
                    messages=messages,
                    parsed=parsed,
                    raw_text=raw_text,
                    temperature=args.temperature,
                    use_json_mode=args.use_json_mode,
                    max_retries=args.semantic_retry,
                )
                if parsed is not None:
                    parsed = enforce_current_record_metadata(
                        parsed=parsed,
                        record=record,
                        original_triplet=normalized_triplet,
                    )
                    model_judge_output_before_fallback = copy.deepcopy(parsed)
                    original_model_verdict = parsed.get("verdict")
                    original_model_corrected = normalize_triplet(parsed.get("corrected_triplet"))
                    parsed = normalize_revise_without_change(parsed)
                    parsed = enforce_current_record_metadata(
                        parsed=parsed,
                        record=record,
                        original_triplet=normalized_triplet,
                    )
                    warnings = validate_judge_output(parsed)
                else:
                    original_model_verdict = None
                    original_model_corrected = None
            else:
                original_model_verdict = None
                original_model_corrected = None
                warnings = [error or "API/JSON parsing failed."]

            auto_fallback_used = False

            if parsed is None or has_hard_format_error(warnings):
                parsed = make_fallback_judge_output(
                    record=record,
                    original_triplet=normalized_triplet,
                    previous_verified_triplets=previous_verified_corrected_triplets,
                    reason_prefix="The API output was missing, invalid, or still used a forbidden delete/empty corrected_triplet after retry.",
                    model_reason=(model_judge_output_before_fallback or {}).get("reason") if isinstance(model_judge_output_before_fallback, dict) else None,
                    model_overall_quality=(model_judge_output_before_fallback or {}).get("overall_quality") if isinstance(model_judge_output_before_fallback, dict) else None,
                    model_major_errors=(model_judge_output_before_fallback or {}).get("major_errors") if isinstance(model_judge_output_before_fallback, dict) else None,
                    model_recommended_strategy=(model_judge_output_before_fallback or {}).get("recommended_strategy") if isinstance(model_judge_output_before_fallback, dict) else None,
                )
                parsed = enforce_current_record_metadata(
                    parsed=parsed,
                    record=record,
                    original_triplet=normalized_triplet,
                )
                warnings = validate_judge_output(parsed)
                auto_fallback_used = True

            # Final corrected triplet used for final output and context.
            final_corrected = normalize_triplet(parsed.get("corrected_triplet"))
            if final_corrected is None:
                final_corrected = fallback_corrected_triplet(
                    record=record,
                    original_triplet=normalized_triplet,
                    previous_verified_triplets=previous_verified_corrected_triplets,
                )
                auto_fallback_used = True

            model_corrected_before_postprocess = normalize_triplet(parsed.get("corrected_triplet"))

            final_corrected = sanitize_triplet(
                triplet=final_corrected,
                record=record,
                previous_verified_triplets=previous_reliable_precursor_triplets,
            )

            final_corrected = restore_supported_original_dehydrogenation(
                original_triplet=normalized_triplet,
                final_triplet=final_corrected,
                previous_reliable_precursor_triplets=previous_reliable_precursor_triplets,
            )

            triplet_postprocess_modified = (
                model_corrected_before_postprocess is not None
                and final_corrected != model_corrected_before_postprocess
            )
            verdict_postprocess_modified = (
                original_model_verdict is not None
                and parsed is not None
                and original_model_verdict != parsed.get("verdict")
            )
            postprocess_modified = triplet_postprocess_modified or verdict_postprocess_modified

            context_safe, chemical_warnings = is_context_safe_triplet(
                triplet=final_corrected,
                previous_verified_triplets=previous_reliable_precursor_triplets,
                smiles=smiles,
                molecule_formula=formula,
            )

            context_reliable_for_precursor = context_safe and is_reliable_for_precursor_context(final_corrected)

            if context_safe:
                previous_verified_corrected_triplets.append(final_corrected)
                if context_reliable_for_precursor:
                    previous_reliable_precursor_triplets.append(final_corrected)

            result_item = {
                "id": data_id,
                "name": name,
                "smiles": smiles,
                "formula": formula,
                "mw": mw,
                "triplet_index": triplet_index,
                "original_triplet": normalized_triplet,
                "judge_output": parsed,
                "model_judge_output_before_fallback": model_judge_output_before_fallback,
                "final_corrected_triplet": final_corrected,
                "auto_fallback_used": auto_fallback_used,
                "semantic_retry_used": semantic_retry_used,
                "postprocess_modified": postprocess_modified,
                "triplet_postprocess_modified": triplet_postprocess_modified,
                "verdict_postprocess_modified": verdict_postprocess_modified,
                "context_reliable_for_precursor": context_reliable_for_precursor,
                "raw_response": raw_text,
                "parse_ok": parse_ok,
                "error": None if parse_ok else error,
                "warnings": warnings,
                "chemical_warnings": chemical_warnings,
                "context_safe": context_safe,
                "previous_verified_corrected_triplets_before_current": previous_before_current,
                "previous_reliable_precursor_triplets_before_current": previous_reliable_before_current,
            }

            full_results.append(result_item)

            print(
                f"Success. verdict={parsed.get('verdict')} "
                f"warnings={len(warnings)} "
                f"chemical_warnings={len(chemical_warnings)} "
                f"context_safe={context_safe} "
                f"context_reliable_for_precursor={context_reliable_for_precursor} "
                f"auto_fallback_used={auto_fallback_used} "
                f"previous_verified_corrected_triplets={len(previous_verified_corrected_triplets)} "
                f"previous_reliable_precursor_triplets={len(previous_reliable_precursor_triplets)}"
            )
            if warnings:
                for w in warnings[:10]:
                    print(f"  [Warning] {w}")
            if chemical_warnings:
                for w in chemical_warnings[:10]:
                    print(f"  [Chemical Warning] {w}")

            if args.save_every > 0 and len(full_results) % args.save_every == 0:
                save_json(full_results, args.output_file)
                corrected_outputs = build_corrected_outputs(
                    input_records=selected_records,
                    full_results=full_results,
                    include_unsafe_in_corrected=args.include_unsafe_in_corrected,
                )
                save_json(corrected_outputs, args.corrected_output_file)
                print(f"Intermediate full results saved to: {args.output_file}")
                print(f"Intermediate corrected results saved to: {args.corrected_output_file}")

            if args.sleep > 0:
                time.sleep(args.sleep)

    save_json(full_results, args.output_file)
    corrected_outputs = build_corrected_outputs(
        input_records=selected_records,
        full_results=full_results,
        include_unsafe_in_corrected=args.include_unsafe_in_corrected,
    )
    save_json(corrected_outputs, args.corrected_output_file)

    print("=" * 80)
    print("All done.")
    print(f"Saved full judge results: {args.output_file}")
    print(f"Saved corrected triplets: {args.corrected_output_file}")


if __name__ == "__main__":
    main()
