# -*- coding: utf-8 -*-

import argparse
import copy
import json
import os
import re
import time
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

from openai import OpenAI


INPUT_FILE = "./difference_types_SMILES/acyclic_alkane.json"
OUTPUT_FILE = "./outputs/acyclic_alkane_judge_results.json"
CORRECTED_OUTPUT_FILE = "./outputs/acyclic_alkane_corrected.json"

MODEL = "gpt-4.1"
TEMPERATURE = 0.0
API_KEY = os.environ.get("OPENAI_API_KEY")


SYSTEM_PROMPT = r"""
You are a professional review-style Judge for EI-MS fragmentation triplets.

Your responsibility is to verify whether an existing triplet is chemically reasonable
and, when it is not reasonable, revise it into a chemically reasonable triplet that
still produces the same target product ion.

You are not a free generator.

You are not required to find the uniquely correct mechanism.

Your task is:

* accept chemically reasonable triplets;
* revise clearly incorrect, unreasonable, or EI-inconsistent triplets;
* always preserve the target product ion unless the product ion formula/m/z itself is inconsistent.

────────────────────────
No-delete principle
────────────────────────

The verdict "delete" is forbidden.

You must output only:

"accept" or "revise"

If the original triplet is chemically unreasonable, do not delete it. Instead, revise
the precursor and/or mechanism so that the same target product ion is generated by
a chemically reasonable pathway.

If the original precursor_mz is wrong, replace it with:
1. a valid previous verified same-carbon higher-hydrogen precursor_mz, or
2. a valid structure-driven smiles_fragment from the molecule.

If the original mechanism is wrong, replace it with the chemically reasonable mechanism.

Never output:
"verdict": "delete"

Never output:
"verdict": "revise",
"corrected_triplet": []

────────────────────────
Core principle
────────────────────────

EI fragmentation often admits multiple chemically reasonable pathways.

Therefore:

Accept any chemically reasonable explanation.

Revise only chemically unreasonable explanations.

If the original triplet is chemically reasonable, accept it even if another explanation
is more common, more canonical, or more preferred.

Do not modify a reasonable triplet merely for stylistic consistency.

A more preferred explanation is not sufficient reason for revision.

Revise only when the original precursor, product ion, or mechanism is chemically
invalid or clearly unreasonable.

────────────────────────
Revision priority
────────────────────────

The Judge must work according to the following priority order:

1. Whether the product ion formula and m/z are internally consistent.

2. Whether the precursor can support the product ion.

3. Whether the mechanism is clearly wrong.

4. Whether a better explanation exists.

Revision is allowed only when one of the first three items has a problem.

Do not revise a reasonable triplet merely because a better explanation exists.

────────────────────────
Key inspection items
────────────────────────

Check:

1. Whether the formula matches the m/z.

2. Whether the product ion carbon number is compatible with the molecule.

3. Whether the precursor can support the product ion.

4. Whether the mechanism conflicts with the structure.

5. Whether the weak-peak-to-strong-peak rule is violated if spectrum evidence is available.

────────────────────────
Alkane rules
────────────────────────

For ordinary C-C bond cleavage in alkanes:

Prefer:

"Sigma-bond cleavage"

For Sigma-bond cleavage, prefer a structure-driven precursor:

"smiles_fragment: <fragment>"

rather than "precursor_mz: <int>".

If the original triplet uses precursor_mz with "Sigma-bond cleavage" and the product
ion is an alkyl cation such as C2H5+, C3H7+, C4H9+, or C5H11+, revise the precursor
to a verifiable smiles_fragment whenever possible.

Do not revise a Sigma-bond cleavage triplet into another precursor_mz-based
Sigma-bond cleavage triplet unless no valid smiles_fragment exists.

────────────────────────
Same-carbon sequential dehydrogenation
────────────────────────

For same-carbon-number sequential hydrogen loss:

Prefer:

"Dehydrogenation / Sequential dehydrogenation"

Examples:

C2H5+ → C2H4+
C2H5+ → C2H3+
C3H7+ → C3H6+
C3H7+ → C3H5+
C3H7+ → C3H3+
C4H9+ → C4H8+
C4H9+ → C4H7+
C5H11+ → C5H9+

Multi-step dehydrogenation allowance:

"Dehydrogenation / Sequential dehydrogenation" may represent multi-step hydrogen
loss within the same carbon-number ion family. The intermediate ion does not need
to be explicitly present if a same-carbon higher-hydrogen precursor is available.

Do not force the precursor to the highest-hydrogen same-carbon ion when the original
precursor_mz is already chemically valid and supported by previous verified triplets.

If the original precursor_mz is already a verified same-carbon higher-hydrogen
precursor for the current product ion, accept it. Do not revise it merely because
another higher-hydrogen precursor also exists.

Use another same-carbon higher-hydrogen precursor only when the original precursor_mz
is unsupported, carbon-incompatible, has no higher hydrogen count than the product,
or is otherwise chemically unreasonable.

Carbon-conservation rule for dehydrogenation:

"Dehydrogenation / Sequential dehydrogenation" must preserve the carbon number
between precursor ion and product ion.

Valid:
C3H7+ → C3H5+
C3H7+ → C3H3+
C4H9+ → C4H7+
C5H11+ → C5H9+

Invalid:
C4H9+ → C3H5+
C3H5+ → C2H5+
C2H5+ → CH3+

If the carbon number changes, do not use "Dehydrogenation / Sequential dehydrogenation".

────────────────────────
Low-mass hydrocarbon ion revision rule
────────────────────────

For alkane-derived spectra, the following ions must not be deleted merely because
the original triplet used an incorrect direct Sigma-bond cleavage mechanism:

C2H4+ (m/z 28)
C2H3+ (m/z 27)
C3H6+ (m/z 42)
C3H5+ (m/z 41)
C3H3+ (m/z 39)
C4H8+ (m/z 56)
C4H7+ (m/z 55)
C5H10+ (m/z 70)
C5H9+ (m/z 69)

If the original precursor is unsupported or chemically invalid and a same-carbon
higher-hydrogen precursor is available in previous_verified_corrected_triplets_for_this_molecule
or in same_carbon_higher_h_precursor_candidates, revise the triplet to use:

"Dehydrogenation / Sequential dehydrogenation"

However, if the original precursor_mz is already supported by a previous verified
same-carbon higher-hydrogen ion, accept the original precursor_mz. Do not revise it
merely because another higher-hydrogen precursor is also available.

Examples:
C2H5+ (m/z 29) → C2H4+ (m/z 28)
C2H5+ (m/z 29) → C2H3+ (m/z 27)
C3H7+ (m/z 43) → C3H5+ (m/z 41)
C3H7+ (m/z 43) → C3H3+ (m/z 39)
C4H9+ (m/z 57) → C4H7+ (m/z 55)
C5H11+ (m/z 71) → C5H9+ (m/z 69)

If no same-carbon higher-hydrogen precursor_mz is available, but
structure_fragment_candidates_for_product contains a valid SMILES fragment, revise
to a structure-driven triplet using that fragment and a chemically reasonable
mechanism.

────────────────────────
Wrong precursor replacement rule
────────────────────────

If the original precursor_mz is chemically unsuitable, but the product ion itself is
chemically reasonable, do not delete.

First check previous_verified_corrected_triplets_for_this_molecule and
same_carbon_higher_h_precursor_candidates.

If a same-carbon higher-hydrogen precursor exists, revise to:

["precursor_mz: <valid_mz>", "Dehydrogenation / Sequential dehydrogenation", "<same product ion>"]

Example:
Original:
["precursor_mz: 42", "Dehydrogenation / Sequential dehydrogenation", "C3H5+ (m/z 41)"]

If precursor_mz: 42 is already supported by a previous verified C3H6+ ion, accept it.
If precursor_mz: 42 is not supported but a previous verified C3H7+ (m/z 43) exists, revise to:
["precursor_mz: 43", "Dehydrogenation / Sequential dehydrogenation", "C3H5+ (m/z 41)"]

Do not delete such a triplet merely because the original precursor_mz is wrong.

If the product is an alkyl cation such as C2H5+, C3H7+, C4H9+, or C5H11+, and
structure_fragment_candidates_for_product contains a matching fragment, revise to:

["smiles_fragment: <fragment>", "Sigma-bond cleavage", "<same product ion>"]

Example:
Original:
["precursor_mz: 41", "Sigma-bond cleavage", "C2H5+ (m/z 29)"]

If the molecule contains a valid "CC" fragment, revise to:
["smiles_fragment: CC", "Sigma-bond cleavage", "C2H5+ (m/z 29)"]

────────────────────────
Unsaturated hydrocarbon ion rule
────────────────────────

For highly unsaturated hydrocarbon cations such as C2H3+, C3H5+, C3H3+, C4H7+,
and C5H9+, do not use ordinary "Sigma-bond cleavage" as the sole mechanism when
a same-carbon higher-hydrogen precursor is available.

If a same-carbon higher-hydrogen precursor is available, prefer:

"Dehydrogenation / Sequential dehydrogenation"

If no such precursor_mz is available, but a valid structure fragment exists, use the
structure fragment as the precursor and revise the mechanism to:

"Dehydrogenation / Sequential dehydrogenation"

rather than leaving the explanation as plain "Sigma-bond cleavage".

This rule is mainly for highly unsaturated ions. It should not override the branched
alkane rule for even-electron ions such as C4H8+, C5H10+, or C6H12+ when structural
evidence supports Sigma-bond cleavage.

────────────────────────
Branched alkane rules
────────────────────────

If the structure contains a tertiary-carbon or quaternary-carbon center, such as:

CC(C)
CC(C)C
CC(C)(C)

then:

"Sigma-bond cleavage"

is allowed as a chemically reasonable explanation.

If the original triplet uses "Sigma-bond cleavage" and the structure indeed contains
a branching center, it should be preferentially accepted.

Do not revise it merely because another explanation is also possible.

For anomalously enhanced even-m/z peaks, for example:

C4H8+ (56)
C5H10+ (70)
C6H12+ (84)

if the original triplet already uses "Sigma-bond cleavage" and the structure supports
it, it should be retained.

Do not force it to be changed to "Dehydrogenation / Sequential dehydrogenation"
unless there is explicit support from a clearly stronger same-carbon-number
precursor ion.

────────────────────────
Heteroatom-containing compound rules
────────────────────────

Only when fragmentation occurs adjacent to a heteroatom is the following mechanism allowed:

"Alpha-cleavage"

For losses such as:

CO
H2O
NH3
H2S
SO2

use:

"Neutral loss"

For pure hydrocarbon molecules, do not use "Neutral loss" for single-H loss that
forms hydrocarbon cations such as CH3+, C2H5+, or C3H7+.

For hydrocarbon alkyl-cation formation, prefer:

"Sigma-bond cleavage"

Reserve "Neutral loss" mainly for stable neutral losses such as CO, H2O, NH3,
H2S, SO2, or clearly defined neutral molecular eliminations.

────────────────────────
Context usage rule
────────────────────────

The user input may contain:

1. all_original_triplets_for_this_molecule:
   All triplets originally generated for the same molecule. Use this only as contextual evidence.

2. previous_verified_corrected_triplets_for_this_molecule:
   Triplets from the same molecule that have already been judged earlier in the current run
   and have passed code-side chemical consistency checks.

3. same_carbon_higher_h_precursor_candidates:
   Previous verified ions that have the same carbon number as the current product ion
   and a higher hydrogen count.

4. structure_fragment_candidates_for_product:
   Verifiable SMILES substrings from the current molecule whose carbon count matches
   the current product ion.

5. previous_reliable_precursor_triplets_for_this_molecule:
   A stricter subset of previous corrected triplets that may be used as strong
   precursor_mz evidence in later ion-evolution decisions.

6. original_precursor_status:
   Whether the original precursor_mz is already supported as a same-carbon
   higher-hydrogen precursor for the current product ion.

When judging the current triplet:
- You may use previous_verified_corrected_triplets_for_this_molecule as reference evidence.
- Prefer previous_reliable_precursor_triplets_for_this_molecule for selecting precursor_mz candidates.
- If original_precursor_status.is_supported=true and the mechanism is
  "Dehydrogenation / Sequential dehydrogenation", accept the original precursor.
  Do not revise it merely because another higher-hydrogen precursor exists.
- Previous verified corrected triplets are reference evidence, not unquestionable ground truth.
- Before using a previous triplet as a precursor, verify:
  1. its product ion m/z matches the current precursor_mz;
  2. its product ion formula has a compatible carbon number;
  3. the mechanism from that precursor to the current product is chemically valid.
- Do not assume any future triplet has already been corrected.
- Do not use previous corrected triplets to justify carbon-number-changing dehydrogenation.
- Do not modify a chemically reasonable triplet merely because previous corrected triplets provide another possible explanation.

────────────────────────
Output format
────────────────────────

You must output strict JSON only, with no extra explanatory text.

The output JSON must follow exactly this structure:

{
  "id": ...,
  "name": "...",
  "smiles": "...",
  "formula": "...",
  "mw": "...",
  "original_triplet": [...],
  "verdict": "accept | revise",
  "reason": "...",
  "corrected_triplet": [...],
  "overall_quality": "...",
  "major_errors": [...],
  "recommended_strategy": "..."
}

Rules:
- verdict must be only "accept" or "revise".
- If verdict="accept", corrected_triplet must be identical to original_triplet.
- If verdict="revise", corrected_triplet must contain the minimally revised valid triplet.
- corrected_triplet must always be a non-empty 3-element list.
- corrected_triplet must preserve the same product ion as original_triplet unless the product ion formula/m/z itself is internally inconsistent.
- major_errors must be an array. If there is no major error, use [].
- Do not output markdown.
- Do not output comments outside JSON.

Forbidden:
- Never output verdict="delete".
- Never output corrected_triplet=[].
    Target ions such as C2H3+, C3H5+, C3H3+, C4H7+, C5H9+.
    These should generally not be explained by plain Sigma-bond cleavage when
    a dehydrogenation-style explanation is available.

    We intentionally use H <= 2C - 1 rather than H < 2C + 1 so that even-electron
    ions such as C4H8+ are not automatically rewritten away from Sigma-bond cleavage.
    Choose a precursor_mz for same-carbon dehydrogenation.

    Priority:
    1. Keep the original precursor_mz if it is already supported by previous verified
       triplets and has the same carbon number with a higher hydrogen count.
    2. Otherwise choose the nearest same-carbon higher-H precursor, rather than
       blindly choosing the highest-H precursor. This avoids over-revising valid
       stepwise dehydrogenation paths.
    Decide whether a corrected triplet is strong enough to be reused as
    precursor_mz evidence in later ion-evolution decisions.

    This is intentionally stricter than context_safe:
    - Molecular ion can seed later context.
    - Sigma-bond cleavage with a structure-driven precursor can seed alkyl ions.
    - Dehydrogenation with precursor_mz can seed later dehydrogenation steps.
    - Dehydrogenation with only a smiles_fragment is kept in final output, but is
      not treated as strong precursor_mz evidence by default.
    For pure hydrocarbons, avoid using Neutral loss to explain simple hydrocarbon
    cation formation such as CH3+, C2H5+, or C3H7+.
    Prevent over-revision to a higher-hydrogen precursor.

    If the original triplet is already a valid same-carbon dehydrogenation step
    supported by reliable previous context, keep the original triplet even if the
    model or postprocessor changed it to a more saturated precursor.
    Lightweight deterministic cleanup:
    - If Sigma-bond cleavage uses an invalid/mismatched smiles_fragment, replace it
      with a valid exact-carbon fragment candidate.
    - If dehydrogenation uses an unsupported precursor_mz but a same-carbon higher-H
      previous precursor exists, replace the precursor_mz.
    Deterministic no-delete fallback. It always returns a non-empty 3-element triplet
    preserving the original product ion.
    If the model says verdict=revise but corrected_triplet is identical to
    original_triplet, normalize the verdict to accept. This avoids inflated revise
    statistics without changing the final triplet.
    Force saved metadata to match the current input molecule.

    This prevents the model from accidentally returning a renumbered id such as 1, 2, 3...
    when the current molecule actually has an original dataset id such as 75, 76, ...
    Official OpenAI API call using the Responses API.

    The command-line argument is still named max_tokens to keep all existing
    retry logic and commands unchanged; it is mapped to max_output_tokens here.
    Retry when the model violates the no-delete / non-empty corrected_triplet schema.
    """
    if parsed is None:
        return parsed, raw_text, ["Initial parsed output is None."], False

    warnings = validate_judge_output(parsed)
    if not has_hard_format_error(warnings):
        return parsed, raw_text, warnings, False

    current_parsed = parsed
    current_raw = raw_text
    current_warnings = warnings

    for retry_idx in range(1, max_retries + 1):
        print(f"[Semantic Retry {retry_idx}/{max_retries}] hard warnings: {current_warnings}")

        retry_messages = messages + [
            {"role": "assistant", "content": current_raw},
            {
                "role": "user",
                "content": (
                    "Your previous JSON violates the required no-delete schema. "
                    "You must output strict JSON only. "
                    "verdict must be only 'accept' or 'revise'. "
                    "The verdict 'delete' is forbidden. "
                    "corrected_triplet must be a non-empty 3-element list. "
                    "Preserve the same target product ion as the original_triplet. "
                    "If the original precursor or mechanism is wrong, revise it using a valid "
                    "previous precursor candidate or a structure-driven smiles_fragment."
                ),
            },
        ]

        retry_parsed, retry_raw, retry_error = call_api_with_token_retry(
            client=client,
            model=model,
            messages=retry_messages,
            temperature=temperature,
            use_json_mode=use_json_mode,
        )

        if retry_parsed is None:
            current_warnings = [f"Semantic retry failed: {retry_error}"]
            continue

        retry_warnings = validate_judge_output(retry_parsed)
        current_parsed = retry_parsed
        current_raw = retry_raw
        current_warnings = retry_warnings

        if not has_hard_format_error(retry_warnings):
            return current_parsed, current_raw, current_warnings, True

    return current_parsed, current_raw, current_warnings, True



def build_corrected_outputs(
    input_records: List[Dict[str, Any]],
    full_results: List[Dict[str, Any]],
    include_unsafe_in_corrected: bool = False,
) -> List[Dict[str, Any]]:
    grouped: Dict[Any, Dict[str, Any]] = {}

    for record in input_records:
        data_id = record.get("id", None)
        grouped[data_id] = {
            "id": data_id,
            "name": record.get("name", ""),
            "smiles": record.get("smiles", ""),
            "formula": record.get("formula", ""),
            "mw": record.get("mw", ""),
            "corrected_triplet": [],
        }

    for item in full_results:
        data_id = item.get("id", None)
        if data_id not in grouped:
            grouped[data_id] = {
                "id": data_id,
                "name": item.get("name", ""),
                "smiles": item.get("smiles", ""),
                "formula": item.get("formula", ""),
                "mw": item.get("mw", ""),
                "corrected_triplet": [],
            }

        final_triplet = normalize_triplet(item.get("final_corrected_triplet"))

        if final_triplet is not None:
            grouped[data_id]["corrected_triplet"].append(final_triplet)

    return list(grouped.values())



def filter_records(records: List[Dict[str, Any]], args: argparse.Namespace) -> List[Dict[str, Any]]:
    selected = []
    for record in records:
        rid = record.get("id", None)
        if args.id_min is not None and isinstance(rid, int) and rid < args.id_min:
            continue
        if args.id_max is not None and isinstance(rid, int) and rid > args.id_max:
            continue
        selected.append(record)

    if args.limit is None:
        return selected[args.start:]
    return selected[args.start:args.start + args.limit]


def main() -> None:
    args = parse_args()

    api_key = API_KEY
    if not api_key:
        raise ValueError("API key is missing. Please pass --api_key or set OPENAI_API_KEY.")

    client = OpenAI(api_key=api_key)

    records = load_json(args.input_file)
    if isinstance(records, dict):
        records = [records]
    if not isinstance(records, list):
        raise ValueError("Input JSON must be a list or a single dict.")

    selected_records = filter_records(records, args)

    full_results: List[Dict[str, Any]] = []
    processed_keys = set()
    existing_by_key: Dict[Tuple[Any, Any], Dict[str, Any]] = {}

    if args.skip_existing and os.path.exists(args.output_file):
        try:
            full_results = load_json(args.output_file)
            for item in full_results:
                key = (item.get("id"), item.get("triplet_index"))
                processed_keys.add(key)
                existing_by_key[key] = item
            print(f"Loaded {len(full_results)} existing judge results.")
        except Exception as e:
            print(f"Failed to load existing output file. Start from empty results. Error: {e}")
            full_results = []
            processed_keys = set()
            existing_by_key = {}

    total_triplets = sum(len(r.get("triplets", [])) for r in selected_records if isinstance(r, dict))

    print("=" * 80)
    print(f"Total selected molecules: {len(selected_records)}")
    print(f"Total triplets to judge: {total_triplets}")
    print(f"id_min={args.id_min}, id_max={args.id_max}, start={args.start}, limit={args.limit}")
    print(f"Model: {MODEL}")
    print("API: OpenAI official Responses API")
    print(f"Full output file: {args.output_file}")
    print(f"Corrected output file: {args.corrected_output_file}")
    print(f"include_unsafe_in_corrected: {args.include_unsafe_in_corrected}")
    print("=" * 80)

    judged_count = 0

    for record_idx, record in enumerate(selected_records, start=1):
        if not isinstance(record, dict):
            continue

        data_id = record.get("id", None)
        name = record.get("name", "")
        smiles = record.get("smiles", "")
        formula = record.get("formula", "")
        mw = record.get("mw", "")
        triplets = record.get("triplets", [])

        previous_verified_corrected_triplets: List[List[str]] = []
        previous_reliable_precursor_triplets: List[List[str]] = []

        if not isinstance(triplets, list):
            print(f"[Skip] id={data_id}: triplets is not a list.")
            continue

        print("=" * 80)
        print(
            f"[Molecule {record_idx}/{len(selected_records)}] "
            f"id={data_id}, name={name}, smiles={smiles}, formula={formula}, mw={mw}, "
            f"triplets={len(triplets)}"
        )

        for triplet_index, triplet in enumerate(triplets):
            normalized_triplet = normalize_triplet(triplet)

            previous_before_current = previous_verified_corrected_triplets[:]
            previous_reliable_before_current = previous_reliable_precursor_triplets[:]

            if normalized_triplet is None:
                fallback = fallback_corrected_triplet(
                    record=record,
                    original_triplet=["", "Sigma-bond cleavage", ""],
                    previous_verified_triplets=previous_verified_corrected_triplets,
                )
                result_item = {
                    "id": data_id,
                    "name": name,
                    "smiles": smiles,
                    "formula": formula,
                    "mw": mw,
                    "triplet_index": triplet_index,
                    "original_triplet": triplet,
                    "judge_output": None,
                    "model_judge_output_before_fallback": None,
                    "final_corrected_triplet": fallback,
                    "auto_fallback_used": True,
                    "raw_response": "",
                    "parse_ok": False,
                    "error": "Invalid input triplet format; expected a 3-element list.",
                    "warnings": ["Invalid input triplet format."],
                    "chemical_warnings": ["Invalid input triplet format."],
                    "context_safe": False,
                    "context_reliable_for_precursor": False,
                    "triplet_postprocess_modified": False,
                    "verdict_postprocess_modified": False,
                    "previous_verified_corrected_triplets_before_current": previous_before_current,
                    "previous_reliable_precursor_triplets_before_current": previous_reliable_before_current,
                }
                full_results.append(result_item)
                continue

            key = (data_id, triplet_index)
            if args.skip_existing and key in processed_keys:
                print(f"[Skip existing] id={data_id}, triplet_index={triplet_index}")
                existing_item = existing_by_key.get(key)
                if existing_item:
                    final_triplet = normalize_triplet(existing_item.get("final_corrected_triplet"))
                    if final_triplet is not None and existing_item.get("context_safe", False):
                        previous_verified_corrected_triplets.append(final_triplet)
                        if existing_item.get("context_reliable_for_precursor", False) or is_reliable_for_precursor_context(final_triplet):
                            previous_reliable_precursor_triplets.append(final_triplet)
                continue

            judged_count += 1
            print("-" * 80)
            print(
                f"[Judge {judged_count}/{total_triplets}] "
                f"id={data_id}, triplet_index={triplet_index}, triplet={normalized_triplet}"
            )
            print(f"Previous verified corrected triplets available: {len(previous_verified_corrected_triplets)}")

            user_prompt = build_user_prompt(
                record=record,
                triplet=normalized_triplet,
                triplet_index=triplet_index,
                previous_verified_corrected_triplets=previous_before_current,
                previous_reliable_precursor_triplets=previous_reliable_before_current,
            )
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ]

            parsed, raw_text, error = call_api_with_token_retry(
                client=client,
                model=MODEL,
                messages=messages,
                temperature=TEMPERATURE,
                use_json_mode=args.use_json_mode,
            )

            model_judge_output_before_fallback = None
            parse_ok = parsed is not None
            semantic_retry_used = False

            if parsed is not None:
                parsed, raw_text, warnings, semantic_retry_used = semantic_retry_if_needed(
                    client=client,
                    model=MODEL,
                    messages=messages,
                    parsed=parsed,
                    raw_text=raw_text,
                    temperature=TEMPERATURE,
                    use_json_mode=args.use_json_mode,
                    max_retries=args.semantic_retry,
                )
                if parsed is not None:
                    parsed = enforce_current_record_metadata(
                        parsed=parsed,
                        record=record,
                        original_triplet=normalized_triplet,
                    )
                    model_judge_output_before_fallback = copy.deepcopy(parsed)
                    original_model_verdict = parsed.get("verdict")
                    original_model_corrected = normalize_triplet(parsed.get("corrected_triplet"))
                    parsed = normalize_revise_without_change(parsed)
                    parsed = enforce_current_record_metadata(
                        parsed=parsed,
                        record=record,
                        original_triplet=normalized_triplet,
                    )
                    warnings = validate_judge_output(parsed)
                else:
                    original_model_verdict = None
                    original_model_corrected = None
            else:
                original_model_verdict = None
                original_model_corrected = None
                warnings = [error or "API/JSON parsing failed."]

            auto_fallback_used = False

            if parsed is None or has_hard_format_error(warnings):
                parsed = make_fallback_judge_output(
                    record=record,
                    original_triplet=normalized_triplet,
                    previous_verified_triplets=previous_verified_corrected_triplets,
                    reason_prefix="The API output was missing, invalid, or still used a forbidden delete/empty corrected_triplet after retry."
                )
                parsed = enforce_current_record_metadata(
                    parsed=parsed,
                    record=record,
                    original_triplet=normalized_triplet,
                )
                warnings = validate_judge_output(parsed)
                auto_fallback_used = True

            final_corrected = normalize_triplet(parsed.get("corrected_triplet"))
            if final_corrected is None:
                final_corrected = fallback_corrected_triplet(
                    record=record,
                    original_triplet=normalized_triplet,
                    previous_verified_triplets=previous_verified_corrected_triplets,
                )
                auto_fallback_used = True

            model_corrected_before_postprocess = normalize_triplet(parsed.get("corrected_triplet"))

            final_corrected = sanitize_triplet(
                triplet=final_corrected,
                record=record,
                previous_verified_triplets=previous_reliable_precursor_triplets,
            )

            final_corrected = restore_supported_original_dehydrogenation(
                original_triplet=normalized_triplet,
                final_triplet=final_corrected,
                previous_reliable_precursor_triplets=previous_reliable_precursor_triplets,
            )

            triplet_postprocess_modified = (
                model_corrected_before_postprocess is not None
                and final_corrected != model_corrected_before_postprocess
            )
            verdict_postprocess_modified = (
                original_model_verdict is not None
                and parsed is not None
                and original_model_verdict != parsed.get("verdict")
            )
            postprocess_modified = triplet_postprocess_modified or verdict_postprocess_modified

            context_safe, chemical_warnings = is_context_safe_triplet(
                triplet=final_corrected,
                previous_verified_triplets=previous_reliable_precursor_triplets,
                smiles=smiles,
                molecule_formula=formula,
            )

            context_reliable_for_precursor = context_safe and is_reliable_for_precursor_context(final_corrected)

            if context_safe:
                previous_verified_corrected_triplets.append(final_corrected)
                if context_reliable_for_precursor:
                    previous_reliable_precursor_triplets.append(final_corrected)

            result_item = {
                "id": data_id,
                "name": name,
                "smiles": smiles,
                "formula": formula,
                "mw": mw,
                "triplet_index": triplet_index,
                "original_triplet": normalized_triplet,
                "judge_output": parsed,
                "model_judge_output_before_fallback": model_judge_output_before_fallback,
                "final_corrected_triplet": final_corrected,
                "auto_fallback_used": auto_fallback_used,
                "semantic_retry_used": semantic_retry_used,
                "postprocess_modified": postprocess_modified,
                "triplet_postprocess_modified": triplet_postprocess_modified,
                "verdict_postprocess_modified": verdict_postprocess_modified,
                "context_reliable_for_precursor": context_reliable_for_precursor,
                "raw_response": raw_text,
                "parse_ok": parse_ok,
                "error": None if parse_ok else error,
                "warnings": warnings,
                "chemical_warnings": chemical_warnings,
                "context_safe": context_safe,
                "previous_verified_corrected_triplets_before_current": previous_before_current,
                "previous_reliable_precursor_triplets_before_current": previous_reliable_before_current,
            }

            full_results.append(result_item)

            print(
                f"Success. verdict={parsed.get('verdict')} "
                f"warnings={len(warnings)} "
                f"chemical_warnings={len(chemical_warnings)} "
                f"context_safe={context_safe} "
                f"context_reliable_for_precursor={context_reliable_for_precursor} "
                f"auto_fallback_used={auto_fallback_used} "
                f"previous_verified_corrected_triplets={len(previous_verified_corrected_triplets)} "
                f"previous_reliable_precursor_triplets={len(previous_reliable_precursor_triplets)}"
            )
            if warnings:
                for w in warnings[:10]:
                    print(f"  [Warning] {w}")
            if chemical_warnings:
                for w in chemical_warnings[:10]:
                    print(f"  [Chemical Warning] {w}")

            if args.save_every > 0 and len(full_results) % args.save_every == 0:
                save_json(full_results, args.output_file)
                corrected_outputs = build_corrected_outputs(
                    input_records=selected_records,
                    full_results=full_results,
                    include_unsafe_in_corrected=args.include_unsafe_in_corrected,
                )
                save_json(corrected_outputs, args.corrected_output_file)
                print(f"Intermediate full results saved to: {args.output_file}")
                print(f"Intermediate corrected results saved to: {args.corrected_output_file}")

            if args.sleep > 0:
                time.sleep(args.sleep)

    save_json(full_results, args.output_file)
    corrected_outputs = build_corrected_outputs(
        input_records=selected_records,
        full_results=full_results,
        include_unsafe_in_corrected=args.include_unsafe_in_corrected,
    )
    save_json(corrected_outputs, args.corrected_output_file)

    print("=" * 80)
    print("All done.")
    print(f"Saved full judge results: {args.output_file}")
    print(f"Saved corrected triplets: {args.corrected_output_file}")


if __name__ == "__main__":
    main()
